### ISSUE TITLE
Make en-analyzer configurable

### ISSUE THREAD

**Issue by ngrunwald** [juji-io/datalevin#102]
Would you be open to make the analyzer used in the search engine configurable at creation? While I understand the aim is not to have everything available like with Lucene, but some control over analysis is necessary for most non english language. At the very  least, some possibility of removing diacritics, and some control on tokenization are necessary, even for simple cases. Specialized tokenization is also often mandatory depending on what's indexed (I'm working with serial numbers right now for example, and getting the right tokens had me playing some non obvious games with character substitution).

A possible implementation would be to just add an `analyzer` field to the `SearchEngine` type. The only breaking change would be changing `add-doc-txs` signature, a private function. I would be willing to submit a pull request if you're interested!

**Comment by huahaiy** [comment]
Sure. That would be a great addition. The analyzer could be passed to `new-search-engine` in an option map `{:analyzer ...}`

**Comment by huahaiy** [comment]
This will be available in next release, which comes out today.

**Comment by ngrunwald** [comment]
well you beat me to it :) Thanks!
I was actually implementing some sugar to easily create analyzers for the standard use case, vaguely in the spirit of lucene so they do not surprise people:
https://github.com/ngrunwald/datalevin/blob/2a341cea77bf12d615ebb4d34771aaac584d6989/src/datalevin/search.clj#L65
Used like this (to emulate the present en-analyzer but slower):
```clojure
(sut/create-analyzer {:tokenizer (sut/create-regexp-tokenizer
                                                                  #"[\s:/\.;,!=?\"'()\[\]{}|<>&@#^*\\~`]+")
                                     :token-filters [sut/lower-case-token-filter
                                                              sut/en-stop-words-token-filter]})
```
Would you be interested by this for the following release?

**Comment by huahaiy** [comment]
Of course. Providing a few built-in analyzers for the common cases would be a great addition. Please continue and we can add them in the following release. Thanks.
