### ISSUE TITLE
Unable to use Java string methods in queries

### ISSUE THREAD

**Issue by crofty** [juji-io/datalevin#103]
I was using datalevin 0.5.x and updated to 0.6.x and some of my queries started failing with:

```
  actual: java.lang.Exception: No namespace: pod.huahaiy.datalevin found
```

I think the issue was because the query was using `.endsWith`:

```
[(.endsWith ^String ?n ?ext)]
```

Which I can replace with `clojure.string/ends-with`, but thought I'd better log it.  It think this is the problematic bit:

https://github.com/juji-io/datalevin/blob/master/src/datalevin/query.cljc#L661
```.clj
(defn- resolve-sym [sym]
  #?(:cljs nil
     :clj (if (namespace sym)
            (when-some [v (resolve sym)] @v)
            ;; handle babashka pod fn
            (when-some [v (ns-resolve 'pod.huahaiy.datalevin sym)] @v))))
```

**Comment by huahaiy** [comment]
Thank you for spotting this. Fix incoming.
