### ISSUE TITLE
String Attributes become keywords sans first character

### ISSUE THREAD

**Issue by kbosompem** [juji-io/datalevin#107]
Simplest way to recreate this is to copy the sample script for the datalevin babashka pod and change the attribute from a keyword to a string.

`#!/usr/bin/env bb

(require '[babashka.pods :as pods])

(pods/load-pod 'huahaiy/datalevin "0.6.1")

(require '[pod.huahaiy.datalevin :as d])

(def conn (d/get-conn "./w0"))

(d/transact! conn [{"greeting" "hello-world"}])

(d/q '[:find ?g :where [_ "greeting" ?g]] (d/db conn))

(println (d/q '[:find ?a ?v :where [_ ?a ?v]] (d/db conn)))

(d/close conn)

(def c2 (d/get-conn "./w0"))

(d/q '[:find ?a ?v :where [_ ?a ?v]] (d/db c2))`

**You get the following results**

`#{[greeting hello-world]}

#{[:reeting "hello-world"]}`

**If you run the same script again you get the following**

`#{[:reeting hello-world] [greeting hello-world]}

#{[nil "hello-world"] [:reeting "hello-world"]}`

Keywords work without issue. Are string attributes not supported in datalevin?

**Comment by huahaiy** [comment]
For now, attributes must be keywords. But we have an issue #74 for this. So this will change in the future.

This requirement is the same as Datascript, Datomic, and so on.

**Comment by nkabir** [comment]
@kbosompem there is the Jet library from @borkdude that works well for easily converting between `edn` and `json`:

https://github.com/borkdude/jet
