### ISSUE TITLE
Expose Iterable / Lazy sequence for get-range - avoid loading table in memory?

### ISSUE THREAD

**Issue by ieugen** [juji-io/datalevin#108]
Hello,

Is it possible to expose an iterator / lazy sequence variant of get-range for key value operations?

LMDB Java exposes this kind of interface via https://www.javadoc.io/doc/org.lmdbjava/lmdbjava/latest/org/lmdbjava/CursorIterable.html .
But fetch-range builds up a vector from it  https://github.com/juji-io/datalevin/blob/ba395d046c83a1077efa4c63808402f09d3383a0/src/datalevin/scan.cljc#L45

```
(type (d/get-range db demographic-tags-table [:all] :string)) => clojure.lang.PersistentVector
```
I'm looking at datalevin kv to do some processing and **avoid** keeping all data in memory. 
However I can't do that currently.

One pattern that I use is:
```clojure

        all-tags (d/get-range lmdb demographic-tags-table [:all] :string)
        ;; split input in batches for efficient SQL processing
        tag-batches (partition-all batch-size batch-size all-tags)
       ;; process each batch
```

**Comment by huahaiy** [comment]
`visit` function can be used to do whatever you want. 

I am open to suggestion on the KV API.

**Comment by ieugen** [comment]
Thanks, I did not know about that since it's not in the API docs.

**Comment by huahaiy** [comment]
It's an oversight on my part. PR welcome.

**Comment by ieugen** [comment]
One issue with visit is that it uses a callback.
So it's hard to implement things like batching. 

I am trying to iterate over entries in a LMDB table and call into an SQL table. 
I am using batching (in my non datalevin) code to improve performance.
I read a bunch of entries and build an SQL that uses the `in` operator:  `select X where y in (set of values)` .

I don't know how to do this easily with the visitor API. 
I am looking at core.async with channels and a batching function but the solution does not look simple. 

I would like to use code like this:
```clojure
   (with-open [all-tags (get-lmdb-lazy-seq lmdb my-table [:all] :string :data)]
   (let ([tag-batches (partition-all batch-size batch-size all-tags)]
     (doseq [batch tag-batches]
       // process batch (doing calls using multiple threads maybe / if possible ?!) 
       (d/transact-kv lmdb updated-data)
      )
    ) 
```

**Comment by ieugen** [comment]
I just remembered another thing so posting here as an idea: ability to reduce over the database range - Implementing `IReduceInit`

**Comment by ieugen** [comment]
Based on the description of https://github.com/juji-io/datalevin/issues/110#issuecomment-1104993021 I think the issue with my code above is that I try to write from multiple threads. 

I rewrote my code to use get-range but I will probably re-try it using `visit` 
Instead of writing in those threads I will post to a channel and pipe that channel to datalevin using a single thread to do the work.

**Comment by huahaiy** [comment]
@ieugen Are you still planning to work on this? Please let me know. Thanks.

**Comment by ieugen** [comment]
Hi, not in the near future. 
I will probably when I get to work with datalevin again. 
If you or anyone else has an interest in this, please go ahead. 
I'll ping when I get a chance to work on this. 

Thanks,
Eugen

**Comment by ieugen** [comment]
I think we can use one of these:
* IDB `iterate-kv` 
* IDB `get-cursor`

**Comment by huahaiy** [comment]
`iterate-kv` should be used, which implements the rather complicated iteration logic, due to many cases that need to be supported. `get-cursor` is very low-level.

Expose `transaction` is an un-related topic, not in scope here.

**Comment by huahaiy** [comment]
We will not add additional functions, since the existing range functions already return Clojure seqs, which are lazy. The main problem is that they may not fit in memory. Therefore, our solution is to automatically spill to disk, but keep the same `seq` API, so there's no change from user's point of view.

The alternative of keeping a read transaction open and returning an iterator is not desirable. LMDB does not like to hold read transaction open for very long, for it essentially keeping an old database copy around, and this blows up the database size very quickly.  Spilling results to a temporary LMDB file does not have this problem. The only overhead is to write the data, but since this is a large result set, which it is slow already. The overhead may not be significant.

**Comment by huahaiy** [comment]
`get-range` and `range-filter` now return a `SpillableVector`, a mutable vector that writes to a temporary LMDB file when the memory pressure is high (default is above 80% of `Xmx`, configurable with `spill-threshold`). This structure implements `IPersistentVector`, so everything works like before. 

Read/write performance is roughly the same as before.

**Comment by huahaiy** [comment]
@ieugen If you really wants to have a function to return an iterator when inside a `with-transaction-kv`, please file a separate issue. Basically, needs some plumbing to expose `iterate-kv`.

**Comment by huahaiy** [comment]
On a second thought, there are some use cases for read-only iterators. OK, we will provide a `range-iterate`  function that does simply wrap `iterate-kv` with the convenient arguments.
