### ISSUE TITLE
[KV] Provide an API similar to clojure swap / swapt-vals with compare and swap semantics ?

### ISSUE THREAD

**Issue by ieugen** [juji-io/datalevin#110]
Hi,

I'm trying to understand LMDB (Datalevin) use cases in concurrent processing (write) scenarios. 
I would like to know if I can do Atomic updates.

Scenario:
* I process some data using multiple threads using Datalevin as a KV store.
* I use string as key and Clojure set as value

What is the outcome if two threads read the same key and try to update it's value after changing the set?

For KV  { "a" -> #{1 2 } } 
If 2 threads read the value for key "a".
One wants to write #{1 2 3}, the other #{1 2 4} ? 

According to http://www.lmdb.tech/doc/index.html "writes are serialized" only one transaction can be done at a time. 

So if I
* open a transaction
*  read,
* write the updated value
* commit
I should be safe and block all the other writers, but not readers.
The readers could read the old value - but only if they don't attempt to get the transaction first which I should block them ?!!??

~~I could not find in the API what happens when a mdb_txn_begin is attempted while another transaction is in progress.~~

> Avoid long-lived transactions. Read transactions prevent reuse of pages freed by newer write transactions, thus the database can grow quickly. Write transactions prevent other write transactions, since writes are serialized.

See http://www.lmdb.tech/doc/index.html

I do appreciate the project exists and I am making use of it.
Would like to use it more but after I understand what I am getting into and what I get (and don't get) from the tool :) . 

https://en.wikipedia.org/wiki/Compare-and-swap
http://www.lmdb.tech/doc/group__mdb.html#ga4fa8573d9236d54687c61827ebf8cac0

**Comment by huahaiy** [comment]
Read and write are independent and do not block each other. Read requires a read transaction. Write requires a write transaction. Reads are concurrent. Basically each reader reads its own copy of the data created at the moment the read transaction starts.  Writes are serialized, only one thread can write at a time.

The above is pretty much the whole story. 

Based on this understanding, I am not sure we need a swap-like function.

**Comment by huahaiy** [comment]
`(with-transaction-kv ...)` and `(with-transaction ...)` are to be implemented. Both take a db and return a modified db.

**Comment by huahaiy** [comment]
Release 0.6.24 added both `with-transaction-kv` and `with-transaction`. Closing.
