### ISSUE TITLE
Query :limit

### ISSUE THREAD

**Issue by mokr** [juji-io/datalevin#126]
Add support for query `:limit` (and related `:offset`)

Based on response on Slack and googled suggestions for Datomic, there seems to be at least two alternatives for implementation:
1. In the map form of `q`. Like `{:query '[:find ... :where ...] ... :limit 20 offset: 40}`
2. In the map form of the query itself like `{:find ... :where ... :limit 20 offset: 40}`.

Alternative 1 reflects the suggestion in [this response in Datomic forum](https://ask.datomic.com/index.php/446/ability-to-limit-the-number-of-results-from-query) (documented [here](https://docs.datomic.com/client-api/datomic.client.api.html#var-q)). One benefit I see for this approach is that it allows you to keep queries in vector form (possibly in a separate file) and only wrap them up in a map when limiting is needed.

If it fits and is not already implemented, support for `:timeout` could be added as well.

**Comment by huahaiy** [comment]
Putting `:limit` etc. in the vector form works too. A vector actually has more freedom than a map, as it does not have to be an even number of items.

**Comment by huahaiy** [comment]
Seems to be related to #117

**Comment by huahaiy** [comment]
`:timeout` is already supported.
