### ISSUE TITLE
Error with edn blob Fail to transact to LMDB: \"key/data pair already exists (-30799)\"

### ISSUE THREAD

**Issue by benjamin-asdf** [juji-io/datalevin#127]
I have this error with a db containing 959 datoms of an "end blob" attribute. The data is an unnested map with keywords -> strings. The strings are quite random, there can be wierd characters in it.

When I deleted some keys of the map I wanted to assert, there was no error so I am fairly certain that some keys in the edn blob caused it. 

I tried to make a repro but this naive attempt does *not* reproduce it: 

```clojure
(ns
    benjamin.datalevin-bug
    (:require
     [datalevin.core :as d]))


(def schema
  {:foo/id {:db/valueType :db.type/string
                          :db/cardinality :db.cardinality/one
                          :db/unique :db.unique/identity}
   :foo/stats {:db/doc "Blob of additional stats"}})


(def get-conn (memoize #(d/get-conn "datalevin/db" schema)))
(def get-db #(d/db (get-conn)))

(d/transact!
 (get-conn)
 [{:foo/id "foo" :foo/stats {:lul "bar"}}])

(dotimes
    [n 100000]
    (d/transact!
     (get-conn)
     [{:foo/id (str "foo" n) :foo/stats {:lul "bar"}}]))

(count (d/q '[:find ?e :where [?e :foo/id _]] (get-db)))
100001
```

**Comment by benjamin-asdf** [comment]
I tried the same code where I have the bug on the repl but by running clojure "clj -X" and there I did not have the bug. Maybe that is a hint.

**Comment by huahaiy** [comment]
Likely a concurrent transaction issue.

**Comment by den1k** [comment]
the memoize call on the conn also seems odd. You can def the conn once and use it from there.

**Comment by huahaiy** [comment]
With recent changes, concurrent writes will be serialized, so this is unlikely to happen. Closing. Reopen if it appears again.
