### ISSUE TITLE
Adding support for BigInt

### ISSUE THREAD

**Issue by currentoor** [juji-io/datalevin#138]
Datalevin looks like a good a fit for an idea I had, but I need to store unsigned 256 bit integers. What would it take to add bigint support? I need to be able to compare these integers inside queries.

Also, in Datomic you can invoke arbitrary methods inside `d/q`, is that possible in Datalevin? I didn't see it in the docs or limitations section.

Because if arbitrary methods are allowed then I could just deserialize the big int as EDN and do my comparison operations on it. But that would have extra overhead.

**Comment by currentoor** [comment]
Asking in slack instead, sorry for the noise.

**Comment by huahaiy** [comment]
It is actually better to keep a record here, as this is public.

**Comment by currentoor** [comment]
Big int’s have a `toByteArray` instance method, would that work? It returns a two's compliment representation of the Big int.

**Comment by huahaiy** [comment]
It certainly helpful. 

While we are at it, we might as well add support for BigDecimal too. This will be a bit tricker.

**Comment by huahaiy** [comment]
Added in release 0.6.17.
