### ISSUE TITLE
Entity IDs not incrementing past 536921769

### ISSUE THREAD

**Issue by crofty** [juji-io/datalevin#140]
Hi Huahai, this was the issue I mentioned on Slack:

I have a really strange issue. I’ve been building up a DB over time and it has suddenly stopped working - eg. when I query to find something that I’ve transacted, it doesn’t find it.
I think that at a certain point the entity ids have stopped incrementing, leading to all sorts of problems with data being overwritten etc.
```
(:tx-data (d/transact! conn [{:a 1}]))
=> [#datalevin/Datom[536921769 :a 1]]
(:tx-data (d/transact! conn [{:b 1}]))
=> [#datalevin/Datom[536921769 :b 1]]
```
The entity id for new data is always 536921769.  If I transact that same data against a new database then I get different entity ids.

**Comment by huahaiy** [comment]
Acknowledged. Will address in the next release.
