### ISSUE TITLE
persist max-tx across application restart

### ISSUE THREAD

**Issue by markusalbertgraf** [juji-io/datalevin#142]
I put a listener on the connection, extract `tx-data` and backup as `datom`s with not just `eav` but also `datom-tx` and `datom-added`.
I expected `datom-tx` to be reliably unique to identify and sort these for analysis, debugging, recovery and replay.
It seems that `max-tx` gets reset to `tx0` every time the application gets restarted (the conn gets created).
This clobbers the log/backup.
I also log who is responsible for a transaction by datom-tx.
At the moment I work around this by reducing `#(max %1 (datom-tx %2))` over the :eavt index and `swap!` this in for `max-tx` befor using the conn.
I know that one day I will call `get-conn` without remembering to calculate and replace `max-tx` first and will clobber my log.
Am I doing something wrong, am I missing something, is this intended?
If not, may I suggest to persist max-tx across restarts?

**Comment by markusalbertgraf** [comment]
When I check `(datoms db :avet)` only 2% of datoms have retained their correct tx.  The rest got changed to tx0.

**Comment by den1k** [comment]
Sounds like what you're implementing is a version of tx log https://github.com/juji-io/datalevin/issues/106

**Comment by markusalbertgraf** [comment]
Yes, we have some similarities.  I am logging every transaction to a separate file though.  I use zfs snapshots and send on the filesystem level, my data is slow but long running.  It should survive a restart.  It does not have to be consumable in production.  It is for backup, debug/audit, dev and disaster recovery purposes (like tx-datom now being "corrupted": after a "fix" the log could be replayed to restore those).  It just needs some reliable marker for ordering and syncing.  I would rather not rely on timestamps, since that can get out of sync easily and I log time additionally anyway.  I actually have a second log in the business domain that also uses tx-datom for correlating the two.  I hoped to continue doing that with datalevin since it saved my butt with a corrupted db before ;-)

**Comment by markusalbertgraf** [comment]
My new workaround is getting max-tx from the existing tx-log on disk when connecting to a db.  We will see how far that gets me.

**Comment by den1k** [comment]
as a quick workaround you could just attach a listener using `(d/listen...)` to the db and `spit` the max-tx into a file.

**Comment by huahaiy** [comment]
Since we are not trying to be immutable db. `tx` is not stored on disk currently. When we address #106, we will surely have a unique `tx`. For now, whatever `max-tx` returned in report should not be relied upon, for I may even further change it, in order to accommodate larger entity id range. Right now, the scheme inherited from Datascript is pretty limiting and weird, as entity id and tx id share the same space. I don't see why it should be like that.

**Comment by huahaiy** [comment]
Now `max-tx` is persistent on disk, so tx id should be unique. Please let me know if it does not work.
