### ISSUE TITLE
Merge datascript entity equality

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#146]
Currently entity equality is simply an id comparison. This breaks equality in reactive applications where updates of other values invalidate equality and allow for changes to propagate downstream. 

datascript merged a change to the implementation. Should this also be added to datalevin? 

https://github.com/tonsky/datascript/issues/433

**Comment by huahaiy** [comment]
Of course. PR welcome.

**Comment by huahaiy** [comment]
Merged
