### ISSUE TITLE
How to optimize fulltext indexing?

### ISSUE THREAD

**Issue by bzg** [juji-io/datalevin#151]
I'm using datalevin as a babashka pod in a script to initialize a db with 5000 entries.

I used the 5000-rows csv example [here](https://sample-videos.com/download-sample-csv.php), to which I added a header line with `id` and `description` for the first two columns (and other names for the rest).

I'm transacting all the data in a single transaction with `(d/transact! conn (into [] csv-data-as-maps))`.

The schema for writing is this:

```clojure
(def schema {:id          {:db/valueType :db.type/string
                           :db/unique    :db.unique/identity}
             :description {:db/valueType :db.type/string
                           :db/fulltext  true}})
```

Full-text indexing seems to take an increasing amount of time, testing from 1000 to 5000 rows:

```
1000: 1,98s user 0,13s system 99% cpu 2,131 total
2000: 7,66s user 0,16s system 99% cpu 7,848 total
3000: 16,81s user 0,17s system 99% cpu 17,009 total
4000: 29,85s user 0,18s system 99% cpu 30,043 total
5000: 45,35s user 0,21s system 99% cpu 45,597 total
```

... compared to 1 sec for 5000 entries when fulltext indexing is not enabled.

Is this expected?

Are there optimizations I can make or limitations I should know to boost fulltext indexing?

Thank you very much!

**Comment by huahaiy** [comment]
Thanks for the report. I will look into this.

**Comment by bzg** [comment]
A quick update on this, tested with the same program/computer but with `(pods/load-pod 'huahaiy/datalevin "0.7.7")` (as more recent versions >0.7.7 are not available yet as pods):

```
1000: 1,64s user 0,17s system 96% cpu 1,870 total
2000: 5,50s user 0,14s system 97% cpu 5,789 total
3000: 12,19s user 0,17s system 98% cpu 12,569 total
4000: 20,96s user 0,23s system 98% cpu 21,472 total
5000: 32,70s user 0,22s system 99% cpu 33,247 total
```

Things seem a bit faster in general compared to my previous report, but the crux of the problem remains: with `:db/fulltext true` for at least one of the attributes, the time it takes to import and index one entry grows with the number of entries added.

Should I requalify this issue as a bug?

**Comment by huahaiy** [comment]
BTW, you don't have to load `dtlv` from pod registry. You can just down load the binary and run as a pod.

**Comment by huahaiy** [comment]
To see if it is a problem with the datalog transaction, try load these text into search engine alone.

**Comment by bzg** [comment]
Thanks a lot for your feedback!  I don't know how to use `dtlv` to load data, I will have a look.

In the meantime, I added 0.7.12 to babashka pods and I updated [the test script](https://github.com/bzg/test-dtlv-load), which you can try easily. 

Tests with 0.7.12 reports the same times for full-text indexing of 1000/2000/... entries.

**Comment by huahaiy** [comment]
Thx for the test case. The bottleneck is the check on whether a doc is already indexed, if so, we remove it. Currently we have to do a full db scan to find this out, hence, the longer and longer indexing time. Next version bump (0.8.0) will address this.  We will need to change index storage format.

**Comment by bzg** [comment]
Ok, I understand now, thanks for the explanations.  Looking forward 0.8.0 and happy to test again.

Btw, I will continue to update babashka pods with latest versions of dtlv if that's okay for you.

**Comment by huahaiy** [comment]
That's a great help. Thank you for doing it.

**Comment by huahaiy** [comment]
0.8.0 should address this issue.

**Comment by bzg** [comment]
Confirmed!  Indexation time seems now to grow linearily wrt the number of items, and is way faster:

```
1000: ./test.clj  0,30s user 0,07s system 97% cpu 0,375 total
2000: ./test.clj  0,54s user 0,08s system 98% cpu 0,626 total
3000: ./test.clj  0,79s user 0,13s system 98% cpu 0,930 total
4000: ./test.clj  1,12s user 0,09s system 99% cpu 1,223 total
5000: ./test.clj  1,42s user 0,13s system 99% cpu 1,559 total
```

Thanks a lot, closing this issue.

**Comment by den1k** [comment]
one Q: on the release

https://github.com/juji-io/datalevin/blob/master/CHANGELOG.md?plain=1#L5

Does the developer need to manually trigger re-indexing or is it automatic?

**Comment by huahaiy** [comment]
`dump` and `load` are functions that can already be called from REPL. `re-index` is not possible, since we don't have the text data any more once the texts are indexed.

**Comment by huahaiy** [comment]
You can file an issue to add such a function, call it `re-index` or something like that. This function basically does a few thing: compact the index by the virtue of loading the datoms in order in a single transaction, optimize the compression dictionary of the index (when we land compression), and re-index the full text datoms.

**Comment by huahaiy** [comment]
We do have `re-index` for a while now.
