### ISSUE TITLE
Expose fulltext fn as `search-datoms`

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#157]
Since it is private I copied the fulltext function into my utils and have since found it very useful to search datoms of a datolog store directly instead of using fulltext in a `d/q`.

So I'm wondering: should `fulltext` or a renamed version of it be exposed in core?

```clojure
(defn search-datoms
  ([db query]
   (search-datoms db query nil))
  ([^DB db query opts]
   (let [^SearchEngine engine (.-search-engine ^Store (.-store db))]
     (search/search engine query opts))))
```

**Comment by bzg** [comment]
I would find this interesting too.

Could you share an example of a use-case you have of this function?

**Comment by huahaiy** [comment]
Sure. Would `fulltext-datoms` be a better name? We have `seek-datoms` already. Don't want to confuse people.

**Comment by den1k** [comment]
Thanks @huahaiy, here's an example of how I would do search with datoms before

```clojure
(defn user-search [db q]
     (sequence
       (comp
         (filter #(str/starts-with? (:v %) q))
         (map #(entity db %)))
       (d/datoms db :ave :user/handle)))
```
