### ISSUE TITLE
native binary should be static on Linux

### ISSUE THREAD

**Issue by huahaiy** [juji-io/datalevin#185]
Can not rely on the right version of glibc on Linux

**Comment by ieugen** [comment]
Hi, I think this would be a great thing since I am currently trying to package datalevin for guix. 

I've ran into this issue while doing a local build: 
```shell
validating RUNPATH of 1 binaries in "/gnu/store/2z4jfqsfxlrfg6sajxq6pm3spsy737fy-datalevin-0.8.4/bin"...
/gnu/store/2z4jfqsfxlrfg6sajxq6pm3spsy737fy-datalevin-0.8.4/bin/dtlv: error: depends on 'libz.so.1', which cannot be found in RUNPATH ()
error: in phase 'validate-runpath': uncaught exception:
misc-error #f "RUNPATH validation failed" () #f 

```

**Comment by ieugen** [comment]
I "fixed" my issue by skipping runtime path validation for guix. 
This is not ideal since it does depend on some local libs. 
Waiting for static builds.
I might make a patch if I have time.

**Comment by huahaiy** [comment]
This is now resolved. Not as easy as one might think. Took a while to get the right version of libstdc++.a
