### ISSUE TITLE
Any way to access database from typed JVM languages such as Java and Kotlin

### ISSUE THREAD

**Issue by FeldrinH** [juji-io/datalevin#186]
Is there any way to communicate with a Datalevin DB from typed JVM languages such as Java, Scala or Kotlin?
I have a project that would greatly benefit from Datalevin, but the project is written in Kotlin.
Given that Clojure is also a JVM language, is there an API for Datalevin that could be called from Kotlin?

I presume https://github.com/juji-io/datalevin/issues/182 could provide an alternative approach for applications written outside of Clojure, but as far as I can tell it is not implemented yet.

**Comment by huahaiy** [comment]
You can use this library from any other JVM language just like any other Clojure library, see for example: 

http://clojure.github.io/clojure/javadoc/clojure/java/api/package-summary.html

**Comment by huahaiy** [comment]
Mentioned in install.md 23043430bb4f1de058aa5875baa2f3da5f0d7fd7
