### ISSUE TITLE
Performance on Windows JDK 8 2-3x slower

### ISSUE THREAD

**Issue by joinr** [juji-io/datalevin#19]
Posting here for posterity, as referenced in the reddit thread [here](https://www.reddit.com/r/Clojure/comments/ilbnb6/datalevin_simple_fast_and_durable_datalog/g3u1ol1/) related to the benchmark fork with datahike added [datalevinbench](https://github.com/joinr/datalevinbench).

Results on ubuntu with same JDK were not reproduced, so it appears to be a lmdb-java windows problem.  
I attempted to see if the new lmbd-java native libs per [lmdb-java #148](https://github.com/lmdbjava/lmdbjava/issues/148) would have an impact to no avail.  Datalevin ran fine with lmbd-java 0.9.24-1 though (benchmarks completed).

**Comment by huahaiy** [comment]
Thank you very much for including Datahike in the benchmark and report this performance issue with Windows. I would appreciate if you could update your reddit post to include your Ubuntu run numbers also. More data points help everyone.

**Comment by joinr** [comment]
No problem.  Updated in reddit thread and on the datalevinbench repo README.

**Comment by huahaiy** [comment]
Thank you. @joinr I appreciate it.

**Comment by huahaiy** [comment]
It may not be a performance issue. Please take a look at https://github.com/joinr/datalevinbench/pull/2

**Comment by joinr** [comment]
That was it indeed.  The assumption about the temp file directory, /tmp, doesn't hold on Windows.  This led to an ever growing database. The interesting news is that a db about 13x the size was still reading about 3x slower than the datascript.  With a fresh db, the results conform to your reported baseline.  No problem with lmdb on windows, just tempfile expectations :)

I added `new-db` to the benchmark to delete the old db (similar to what datahike is doing), which technically adds a little to the measurements, but the results are apparently identical (e.g. deletion isn't a problem).  The "real" fix would be to implement a portable temp file pathway for the db (I think the storage/open function called with nil directory creates a tmp/uuid file, so that would probably be the only place to define a wrapper that leverages (System/getProperty "java.io.tmpdir") to construct a portable temp directory.

**Comment by joinr** [comment]
Updated reddit thread and readme for posterity.

**Comment by huahaiy** [comment]
Great. Thanks!
