### ISSUE TITLE
I managed to find a difference in how lookup refs are treated between datascript and datalevin

### ISSUE THREAD

**Issue by Folcon** [juji-io/datalevin#194]
Not sure why this is, but if the first transaction has gone through it seems to work, but the initial one can blow up.

This was the smallest repro that I could make, hopefully it helps track down the issue!

```clojure
(let [tx-data
      [{:a 0, :lookup-id [0 0]}
       {:a 0, :lookup-id [0 1]}
       {:a 0, :lookup-id [1 0]}
       {:a 0, :lookup-id [1 1]}
       {:ref-id [:lookup-id [0 1]]}]
      schema {:ref-id {:db/valueType :db.type/ref}
              :lookup-id {:db/unique :db.unique/identity}}]
  [(datascript.core/db-with
     (datascript.core/empty-db schema)
     tx-data)
   (try
     (datalevin.core/db-with
       (datalevin.core/empty-db "/tmp/test-db" schema)
       tx-data)
     (catch Exception e
       (println :ex-cause (ex-cause e))
       (println :ex-data (ex-data e))
       (println :tx-data (pr-str tx-data))))])
:ex-cause nil
:ex-data {:error :entity-id/missing, :entity-id [:lookup-id [0 1]]}
:tx-data [{:a 0, :lookup-id [0 0]} {:a 0, :lookup-id [0 1]} {:a 0, :lookup-id [1 0]} {:a 0, :lookup-id [1 1]} {:ref-id [:lookup-id [0 1]]}]
=>
[#datascript/DB{:schema {:ref-id #:db{:valueType :db.type/ref}, :lookup-id #:db{:unique :db.unique/identity}},
                :datoms [[1 :a 0 536870913]
                         [1 :lookup-id [0 0] 536870913]
                         [2 :a 0 536870913]
                         [2 :lookup-id [0 1] 536870913]
                         [3 :a 0 536870913]
                         [3 :lookup-id [1 0] 536870913]
                         [4 :a 0 536870913]
                         [4 :lookup-id [1 1] 536870913]
                         [5 :ref-id 2 536870913]]}
 nil]
```

**Comment by huahaiy** [comment]
This is related to comparison of Clojure data structures. In this case, comparing `[0 1]` and `[1 0]` should return `-1`, intuitively. 

With arbitrary things in data, it's a complicated subject that we will deal with on a case by case basis. The reasons are the following:

Datascript's comparison code does not work in some of our use cases, as it simply throws when data types in collections do not match. We want a more robust solution.

There's also a performance trade-off, as such comparisons is at the bottom of data processing and a slight change can drastically change the performance, we will thread carefully.

Let me think of a way to fix this without degrade performance too much.
