### ISSUE TITLE
Portable tempfile path

### ISSUE THREAD

**Issue by joinr** [juji-io/datalevin#20]
Current implementation implicitly expects that "/tmp" is system temporary file, which holds except for Windows.  On windows it's typically c:/users/joinr/AppData/local/Temp I think.  JVM will tell you via (System/getProperty "java.io.tmpdir").  from #19

**Comment by huahaiy** [comment]
All use of temporary dir changed to use `util/tmp-dir`, closing.

**Comment by joinr** [comment]
resubmitted in #22 due to regression that unintentionally broke windows and fixed linux (I think the original pr fixed windows and broke linux).  This works on both consistently now, and has reader conditionals around the java stuff.
