### ISSUE TITLE
Heap memory growth

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#204]
running this code repeatedly lead to ever increasing heap usage. version "0.8.12"

slack [ref](https://clojurians.slack.com/archives/C01RD3AF336/p1682363516634429?thread_ts=1682362090.719989&cid=C01RD3AF336)

```clojure
(defonce test-conn
  (d/create-conn nil))

;; run this many times while watching heap
;; in VisualVM and running GC
(dotimes [i 10000]
  (d/transact! test-conn [{:foo i}]))
```

**Comment by huahaiy** [comment]
Cannot reproduce the behavior of heap keeping increasing with this code. The heap goes up and down when one keeps running this code. Also, this code only increases a few hundred MiB at each run. Then it goes down. I cannot imagine this will lead to OOM. 

Now I change it to this: 

```
(dotimes [j 100]
    (dotimes [i 10000]
      (transact! test-conn [{:foo i}])))
```
It takes a long time to run. Intially, the heap goes up, then back down to 1GB, and stay there until the end.

**Comment by huahaiy** [comment]
Fixed.
