### ISSUE TITLE
Question: can I tell from tx-data returned by `transact!` if an attributed was added or not?

### ISSUE THREAD

**Issue by kipz** [juji-io/datalevin#207]
In Datomic, it's possible to look at the transaction result and see if a particular datom was "changed" in the transaction. So if it's new, or updated (implicit retract and add), this is evident in tx-data. Similarly, if it was retracted, this is evident in tx-data.

Is this possible with Datalevin? 

I see `datom-added` in one of the Protocols, but that doesn't seem to do what I want, though I'd be interested in know what it does to.

Thanks in advance.

**Comment by den1k** [comment]
@kipz easy. You can call `:added` on the datom. if that is true it has been added. if it is `false` it has been removed. The datom will show up twice if it has been replaced, once with both `true` and `false` values for `:added`

```clojure
(defonce test-conn (d/create-conn))
(d/datoms @test-conn :ave)
(def report (d/transact! test-conn [{:foo "bar"}]))

(map :added (:tx-data report))
; => (true)
(def report2 (d/transact! test-conn [{:db/id 1
                                      :foo   "beep"}]))

(map :added (:tx-data report2))
; => [#datalevin/Datom[1 :foo "bar"] #datalevin/Datom[1 :foo "beep"]]

(defn tx-report->change-status [{:keys [tx-data] :as tx-report}]
 (update-vals (group-by :e tx-data)
              #(case (into #{} (map :added) %)
                 #{true false} :changed
                 #{false} :retracted
                 #{true} :added)))

(tx-report->change-status report2)
;; => {1 :changed}

(def report3 (d/transact! test-conn [[:db/retractEntity 1]]))
(tx-report->change-status report3)
; => {1 :retracted}
```

**Comment by kipz** [comment]
Thanks @huahaiy and @den1k, the example above only works the first time a value is transacted, subsequent times the same value is transacted, it's still showing as `added`, and I think this differs from Datomic.

```clojure
  (defonce test-conn (d/create-conn))
  (d/datoms @test-conn :ave)
  (def report (d/transact! test-conn [{:foo "bar"}]))

  (map :added (:tx-data report))
  ;; => (true)
  (def report2 (d/transact! test-conn [{:db/id 1
                                        :foo   "bar"}]))

  (map :added (:tx-data report2))
  ;; => (true) 
  ;; expected (false) because the data was not changed, and I think this is different from Datomic
```

**Comment by huahaiy** [comment]
Correct, Datalevin is not an immutable database. We should not expect everything be same as Datomic.

**Comment by kipz** [comment]
Thanks @huahaiy. I totally get that it's not the same as Datomic, but I'm not sure if this is a question of immutability. Isn't it about what is returned in the different scenarios?

1. new datom => added: true
2. changed datom => added: false, added: true (for each datom)
3. unchanged => added: false

I get that this would be a change of behavior, and I get that being the same as Datomic isn't a goal here in general, but using this kind of output from databases is a common use case, and computing it should be easy in the DB (as with value changes), but very expensive to do form the outside: query all datoms in the TX before and after the transaction and doing a diff.

**Comment by huahaiy** [comment]
You can file an issue. We may get around to it. 

For unchanged, the desired behavior is to not show up in `:tx-data`, instead of its being `:added false`. Because Datom object use the sign of tx id to indicate if it is added or deleted. There's no third state.

Right now, an unchanged datom shows up in tx-data, because we force transacting it to get around a subtle bug, if I remember correctly. Basically, we use Datascript's transaction logic for the most part for now, and it transacts one datom at a time, which is different from our batch transaction logic. In order to get around that without rewrite transaction logic, we opt to transact a datom even if it is found in the DB.

We will get around to revamp the transaction logic, after we replace Datascript's query engine first. One thing at a time.

**Comment by kipz** [comment]
Understood, thanks @huahaiy.

**Comment by huahaiy** [comment]
That would be a bigger change. 

As mentioned, a Datom has only two state for now. `added: false` actually means `deleted`.

**Comment by kipz** [comment]
@huahaiy totally, that makes sense, sorry.

I've tried locally by changing: 

https://github.com/juji-io/datalevin/blob/96775af84b88996fcb0e91ca4a87913d457476f6/src/datalevin/db.cljc#L856

to not bother adding datoms to the report if the values are the same, and this seems to work for me at first glance.

Can you think of any other implications?

**Comment by kipz** [comment]
This is the related issue you were referring to I guess?

https://github.com/juji-io/datalevin/issues/192

**Comment by huahaiy** [comment]
Correct. If you can avoid transacting it while not inducing this bug, I am happy to merge.

**Comment by huahaiy** [comment]
OK, we now special case #192 for now. It may have some performance hit, but at least the desired cases are supported.

**Comment by kipz** [comment]
Thanks so much @huahaiy! :)
