### ISSUE TITLE
No such var: c/+in-tx-overflow-times+

### ISSUE THREAD

**Issue by joshcho** [juji-io/datalevin#210]
I am getting this error for versions >= 0.8.10 during compilation.

```
Syntax error compiling at (datalevin/lmdb.cljc:166:1).
No such var: c/+in-tx-overflow-times+
```

**Comment by huahaiy** [comment]
Please use the latest version of Clojure.

**Comment by joshcho** [comment]
This happens by just requiring datalevin.core. Also my clj version is 1.11.1.1273 and my lein version is Leiningen 2.10.0 on Java 11.0.18 OpenJDK 64-Bit Server VM.

**Comment by huahaiy** [comment]
Please post the step to produce this.

**Comment by huahaiy** [comment]
Cannot reproduce with the 0.8.16.

**Comment by joshcho** [comment]
Not an issue with 0.8.16; cannot reproduce on my machine either.
