### ISSUE TITLE
The difference between :db.unique/identity and :db.unique/value for  :db.type/tuple

### ISSUE THREAD

**Issue by Guliy** [juji-io/datalevin#220]
We have a schema where attribute :item/name+type is defined as { :db/unique :db.unique/identity}

```clojure
(def schema
    {:item/category {:db/valueType :db.type/keyword}
     :item/name  {:db/valueType :db.type/string}
     :item/type  {:db/valueType :db.type/string}
     :item/name+type  {:db/valueType   :db.type/tuple
                       :db/tupleAttrs  [:item/name :item/type]
                       :db/cardinality :db.cardinality/one
                       :db/unique      :db.unique/identity
    ...
     :stash/item {:db/valueType :db.type/ref
                  :db/cardinality :db.cardinality/one}
}})
```

Then, we are trying to write a few facts into the database

```clojure
(d/transact! @conn
               [{:db/id -1,
                 :stash/bot [:bot/name "bot-name1"]
                 :stash/count 4
                 :stash/item {:item/category :currency
                              :item/name "Divine"
                              :item/type "Divine"}}
                {:db/id -2,
                 :stash/bot [:bot/name "bot-name2"]
                 :stash/count 2
                 :stash/item {:item/category :currency
                              :item/name "Divine"
                              :item/type "Divine"}}])
```
and get an error

 `Cannot add #datalevin/Datom [34 :item/name+type ["Divine" "Divine"]] because of unique constraint: true`

As far as I understand, this behaviour is expected if `:item/name+type` was defined as  `:db/unique      :db.unique/value` not `:db/unique  :db.unique/identity`, judging by an excerpt from the datomic documentation:

> * :db.unique/value - only one entity can have a given value for this attribute. Attempts to assert a duplicate value for the same attribute for a different entity id will fail. More documentation on unique values is available [here](https://docs.datomic.com/pro/schema/identity.html#unique-values).
> * :db.unique/identity - only one entity can have a given value for this attribute and "upsert" is enabled; attempts to insert a duplicate value for a temporary entity id will cause all attributes associated with that temporary id to be merged with the entity already in the database

Of course, there is a workaround but it looks like a bug.

**Comment by huahaiy** [comment]
This is expected, as you have two entities that having the same :item/name+type value. This violates :db.unique/identity requirement, because there can be only one entity having that value, it's an identity of the entity, after all.
