### ISSUE TITLE
Datalevin doesn't play well with sci (through malli)

### ISSUE THREAD

**Issue by jeroenvandijk** [juji-io/datalevin#230]
Thank you for creating Datalevin.

I ran into the error `"No reader function for tag datalevin/regex"` when using Datalevin in combination with a Malli validation. 

The Slack discussion can be [found here](https://clojurians.slack.com/archives/C01RD3AF336/p1698130243018619).

The problem is that Datalevin adds a `print-method` [for all regular expressions](https://github.com/juji-io/datalevin/blob/36ea8e49c45074472813de9975f3a3c8e5526f02/src/datalevin/bits.cljc#L80). The resulting serialized form (e.g. `# datalevin/regex "foo"`) cannot be understood by [Sci which is used by Malli under the hood](https://github.com/metosin/malli/blob/master/src/malli/sci.cljc#L4-L16).

This issue can be reproduced by executing [the following gist](https://gist.github.com/jeroenvandijk/71cea769b3b2850f896cd501a32395a5): 
```
git clone https://gist.github.com/jeroenvandijk/71cea769b3b2850f896cd501a32395a5
clj -X magic-error/show-me
```

The gist also has a workaround.

**Comment by huahaiy** [comment]
Because some data contains regex, in order to store and retrieve such data, print-method for regex was added, e.g. they are often used in transaction functions. 

We can make this print-method optional for regex in order to support your use case. I can add a function `set-confg` to allow setting some global configurations. In this case, `(set-config :store-regex? false)` can be called to disable adding print-method for regex.

**Comment by jeroenvandijk** [comment]
I understand it is part of the serialization format. I would argue though that including the Datalevin namespace in your Clojure project should not break something that can be considered standard Clojure code. Especially for new users it would not be obvous to use your proposed setting. Also, what do you do when you need both. Maybe there is an alternative solution (idea below)?

Note: I haven't touched Datalevin much so I'm not sure about the impact of any change to this project. 

```clojure
;; in datalevin.bits

;; Don;t interfere with Clojure by default
(def :^dynamic *datalevin* false)

;; For Datalevin types *datalevin* is true
(defmethod print-method Indexable
  [^Indexable i, ^Writer w]
  (.write w "#datalevin/Indexable ")
  ;; This is Datalevin territory
  (binding [*datalevin* true]
    (.write w (pr-str (pr-indexable i)))))


;; Depending on the *datalevin* value we will adapt printing for regex (and maybe others
(defmethod print-method Pattern
  [^Pattern p, ^Writer w]
  (if *data-levin*
    (doto w
      (.write "#datalevin/regex ")
      (.write "\"")
      (.write ^String (s/escape (.toString p) {\\ "\\\\"}))
      (.write "\""))
    ;; => Default Clojure's print behaviour here
    (.write w (str "#\"" (.toString p) "\"")))

```

**Comment by huahaiy** [comment]
As per discussions on slack, requiring people to have a binding to use Datalevin functions seems a bit excessive, so we will keep the `set-config` function proposal, and hope people who have similar issues will land it here.

**Comment by den1k** [comment]
> Because some data contains regex, in order to store and retrieve such data, print-method for regex was added, e.g. they are often used in transaction functions.

is this because pr-str is used to write this data? Would it help to use custom functions similar to nippy's serialize?

**Comment by huahaiy** [comment]
Using print for regex is when importing/exporting data as text, so it is possible to only add the print-method when exporting.

**Comment by huahaiy** [comment]
Just limit the change of print-method to dumping the DB.
