### ISSUE TITLE
Options not recovered after automatic reconnection

### ISSUE THREAD

**Issue by euccastro** [juji-io/datalevin#241]
I've been noticing that when I create a connection using `(d/get-conn "dtlv://datalevin:xxxx@host/db" schema {:validate-data? true :auto-entity-time? true}) ` and hold on to it for long, at some point the `:auto-entity-time?` flag stops working.
That is, immediately after creating the connection, any newly created entities get a `:db/created-at` and a `:db/updated-at`, but at some point down the road any new entities still get created correctly but without those attributes.

I inquired about this in the Clojurians slack and @huahaiy replied:

> It is possible that this is a bug, the options are not recovered after an automatic reconnection happens, please file an issue

**Comment by huahaiy** [comment]
Please let me know if 0.8.28 fixes this.
