### ISSUE TITLE
Writing after re-opening a connection overwrites entities

### ISSUE THREAD

**Issue by russmatney** [juji-io/datalevin#25]
Thanks for creating datalevin! I've enjoyed toying with it for the last few days, great work!

After closing and re-creating a connection, the db seems to start overwriting entity data, and fails to update `:db.type/instant` values. It looks like the recreated connection has lost its state and indexes.

I created a quick [reproduction here](https://github.com/russmatney/datalevin-conn-reproduction/blob/master/src/dlt/core.clj).

The symptom was an error while transacting:

```
Unhandled clojure.lang.ExceptionInfo
   Fail to transact to LMDB: "\"Error putting r/w key buffer of datalevin/eav:
   java.lang.Long cannot be cast to java.util.Date\""
   {:txs
    [[:del
      "datalevin/eav"
      #object[datalevin.bits.Indexable 0x5b5ff66f "datalevin.bits.Indexable@5b5ff66f"]
      :eav] .... etc
```
The 'overwritten' entities are likely the result of the new connection re-using old entity ids.

**Comment by huahaiy** [comment]
Release 0.3.7 fixes this. Thanks for reporting.

**Comment by russmatney** [comment]
Thanks for the quick fix!!

**Comment by huahaiy** [comment]
Thanks for the test case, so I could find the problem quickly.
