### ISSUE TITLE
Datalevin hangs when searching for unknown field

### ISSUE THREAD

**Issue by m3tti** [juji-io/datalevin#274]
Hi awesome datalevin folks,

i have currently the problem that if i trigger a search where there is no value in the database the query hangs and destroys my repl session. So that i can't reavaluate my query. I'm using currently babashka to do that.
```
(require '[babashka.pods :as pods])

(pods/load-pod 'huahaiy/datalevin "0.9.10")

(require '[pod.huahaiy.datalevin :as d])

(def db (d/get-conn "/tmp/testdb"))

(d/transact! db [{:test/name "hello"}
                 {:test/name "hello2"}
                 {:test/name "hello2"}])

;; executes
(d/q '[:find ?name
       :in $
       :where
       [?e :test/name ?name]]
     (d/db db))

;; hangs :/
(d/q '[:find ?some
       :in $
       :where
       [?e :test/some ?some]]
     (d/db db))
```
Can someone explain or tell me why the repl session hangs?

EDIT: issue was encountered in babashka v1.3.190

Best Regards,
Mathaeus

**Comment by bzg** [comment]
I confirm the bug, I encountered it very recently.
