### ISSUE TITLE
Dead link in README for Datomic value types

### ISSUE THREAD

**Issue by simongray** [juji-io/datalevin#275]
In this part of the README

> Respects :db/valueType. Currently, most [Datomic® value types](https://docs.datomic.com/on-prem/schema.html#value-types) are supported, except uri. Values of the attributes that are not defined in the schema or have unspecified types are treated as [EDN](https://en.wikipedia.org/wiki/Extensible_Data_Notation) blobs, and are de/serialized with [nippy](https://github.com/ptaoussanis/nippy).

[Datomic® value types](https://docs.datomic.com/on-prem/schema.html#value-types) leads to a "Document not found" page. I'm assuming Cognitect rewrote the documentation and killed the old page.

**Comment by simongray** [comment]
Perhaps it should be changed to this?

https://docs.datomic.com/schema/schema-reference.html#db-valuetype

**Comment by huahaiy** [comment]
Thanks.
