### ISSUE TITLE
Weird transaction result when Integer used as value for :db.unique/identity attribute

### ISSUE THREAD

**Issue by zelark** [juji-io/datalevin#285]
Let's say we have the following schema and connection

```
(def schema
  {:user/id       {:db/valueType :db.type/long
                   :db/unique    :db.unique/identity}
   :user/username {:db/valueType :db.type/string
                   :db/unique    :db.unique/value}
   :user/ref-user {:db/valueType   :db.type/ref
                   :db/cardinality :db.cardinality/many}})

(def conn (d/create-conn "dtlv" schema))
```

Then we transact our first user

```
(d/transact! conn [{:user/id 1
                    :user/username "Eve"}])
```

Everything is good so far.

Imagine we got some data for a second user Alice, which was invited by Eve. And for some reason Alice's `user/id` has type `java.lang.Integer`

```
(d/transact! conn [{:db/id "alice"
                    :user/id (Integer. 2)
                    :user/username "Alice"}
                   {:user/id 1
                    :user/ref-user ["alice"]}])
```

And if we check it, we will see Alice refers to herself, which is weird because Eve should refer to Alice.

```
(-> (d/entity (d/db conn) [:user/id 2])
    (d/touch))

;; unexpected result
{:db/id 8,
 :user/id 2,
 :user/ref-user #{#:db{:id 8}},
 :user/username "Alice"}
```

Things are getting more interesting if **we change the order of tx-data**

```
(d/transact! conn [{:user/id 1
                    :user/ref-user ["bob"]} ; Eve's tx-data goes first
                   {:db/id "bob"
                    :user/id (Integer. 3)
                    :user/username "Bob"}])
                    
(-> (d/entity (d/db conn) [:user/id 3])
    (d/touch))
    
;; expected result
{:db/id 9
 :user/id 3,
 :user/username "Bob"}
```

And now Eve refers to Bob

```
{:db/id 7,
 :user/id 1,
 :user/ref-user #{#:db{:id 9}},
 :user/username "Eve"}
```

In my real case I ran into this issue cause I used Cheshire. And it parses small numbers as Integers as Jackson does

```
(type (json/parse-string "1")) ; => java.lang.Integer
```
And seems there is no way to change this behaviour right now https://github.com/dakrone/cheshire/issues/105

However, from Clojure's perspective numbers are equal regardless its types

```
(= (Integer. 1001) (Long. 1001)) ; => true
```

So I believe, Datalevin should treat them equally to get predictable result. It took me almost a day to understand the problem, hope it will save some time for someone.

**Comment by zelark** [comment]
Thanks for you advice. `:validate-data? true` is a good option. However, as I said above, from Clojure's perspective Integer and Long are equal. Eventually type's of integers shouldn't affect anything if integers are equal with `=` operator.

I checked the same example with datomic local. It works fine with `Integer` values.

```
(d/pull (d/db conn) '[:user/id :user/username :user/ref-user] [:user/id 1])

;; => #:user{:id 1, :ref-user [#:db{:id 92358976733262} #:db{:id 101155069755469}], :username "Eve"}
```

**Comment by andersmurphy** [comment]
So:

`int` -> `long` when passing into `:db.type/long`

and:

`int/long` -> `bigint` when passing into `:db.type/bigint`

and:

`bigint` -> `long` when passing into `:db.type/long` 

Do you know what datomic local does in these cases?

**Comment by huahaiy** [comment]
The above proposal sounds reasonable.

**Comment by zelark** [comment]
@huahaiy thank you for a quick response and the implementation. I'm looking forward for the next release to test it out. I saw you added some more handy coercions. It's nice!

**Comment by andersmurphy** [comment]
> @huahaiy thank you for a quick response and the implementation. I'm looking forward for the next release to test it out. I saw you added some more handy coercions. It's nice!

Yeah, the uuid coescion is nice, I like storing them as strings (so that I can change the implmentation if need be) and I always forget to `str` them after creation. 

Btw, if you want to use the changes in your projet now you can use git deps:

```
datalevin/datalevin {:git/url "https://github.com/juji-io/datalevin"
                                 :git/sha "6ff59686da20051b302170f7780852fa870a0019"}
```

Less useful on datalevin where the releases are so often. But for projects with slower release cadence it can save having to wait for a new release.
