### ISSUE TITLE
speculative transactions

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#31]
I saw that `with` and `db-with` have no-doc metadata:

https://github.com/juji-io/datalevin/blob/master/src/datalevin/core.cljc#L194-L211

Is that because datalevin does not support speculative transactions / immutability?

**Comment by huahaiy** [comment]
Correct. Datalevin is mutable. There's no speculative transactions, for transaction id is not stored.

**Comment by huahaiy** [comment]
There are now two ways to do speculative transactions:

1. `tx-data->simulated-report` will return a transaction report without actually commit the changes.
2. `with-transaction` combined with `abort-transact` will allow you do the transaction, see its effects, then abort the transaction.
