### ISSUE TITLE
Comparing dates in :where clause

### ISSUE THREAD

**Issue by pm4r** [juji-io/datalevin#32]
I have a query to which I pass some Date, by which I would like to filter some date attribute. In Datomic I can use predicates like [(.after ?myattr ?dateparam)] but doing it here I get error:
`Execution error (ExceptionInfo) at datalevin.query/filter-by-pred (query.cljc:577).
Unknown predicate '.after in [(.after ?tm ?d)]`

Type hints in query don't change anything. Passing long value as a date gives:

`Execution error (ClassCastException) at datalevin.query/-call-fn$fn (query.cljc:564).
java.util.Date cannot be cast to java.lang.Number`

So how could I filter dates within query?

**Comment by huahaiy** [comment]
Thanks. I can reproduce this. Will take a look.

**Comment by huahaiy** [comment]
Fixed in 0.3.16. Java interop calls are allowed as function calls in where clause.

**Comment by pm4r** [comment]
It works, thank you. However performance is really bad. I have couple of queries by which I compare 3 different storage engines. Datalevin is faster about 30-50% compared to the next one, but on query where dates are used in :where clause it's about 200-1000x slower than expected and all subsequent query calls becomes even slower so something is clearly wrong here. It doesn't matter if I compare dates or longs (by .getTime calls).

Also by accident it turns out query parser fails very late (Insufficient bindings) which happend when I used wrong var name by mistake which was after clause with dates (which takes majority of time). It looks like query is not validated before being issued, but at the moment of actual call. Not a big deal as this kind onf mistakes shows up early during development but was unexpected.

**Comment by huahaiy** [comment]
Released 0.3.17 to improve the interop performance a bit. Please let me know if it helps.

Please also note that Datascript query engine is in use for the most part, which leaves a lot of efficiency on the table. We are going to do develop a new query engine that will push such filtering clauses down to index scan stage. In this particular case, we won't be working with Date, but just do bits comparison, which should be a few order of magnitude faster. This new engine is targeted release 0.5.0.

**Comment by pm4r** [comment]
Well done! Query speed for dates is know within expected range. This project looks really promising. I will keep an eye for further updates.

**Comment by huahaiy** [comment]
Thank you for the encouragement.
