### ISSUE TITLE
Package binary

### ISSUE THREAD

**Issue by huahaiy** [juji-io/datalevin#39]
We should make dtlv command line tool available for users to easily install, including installing the dependency (LMDB). For MacOS and Linux, we can use homebrew. For Windows, need to figure out.  Also release datalevin as a babashka pod.

**Comment by borkdude** [comment]
@huahaiy A thought: I think you can maybe bundle the LMDB lib (if the license allows it) and spit it out it to `~/.dtlv/liblmbd.dylib` on startup if it isn't there yet, and then dynamically load this library. 

This is the approach that spire takes:

https://github.com/epiccastle/spire/blob/7439a0a17c25fd54e3d86712d2a44b38fd71877a/src/clj/spire/config.clj#L23-L56

Optionally you can also look in some of the directories where this lib is often found or make that configurable using an env var.

**Comment by borkdude** [comment]
It's also pretty interesting how the xerial sqlite lib does this. It packages the sqlite lib along in the resources:

https://github.com/xerial/sqlite-jdbc/blob/6ca62fd07bf7faf58e923ba8651757621ffc693c/src/main/java/org/sqlite/SQLiteJDBCLoader.java

It's not entirely clear to me how the lib gets loaded from the resource though.

**Comment by borkdude** [comment]
Found it: 

https://github.com/xerial/sqlite-jdbc/blob/6ca62fd07bf7faf58e923ba8651757621ffc693c/src/main/java/org/sqlite/SQLiteJDBCLoader.java#L344

It seems they use a similar approach: export the OS-specific lib to a temp folder and then load it. I think exporting it to a fixed location would be more time saving though.

**Comment by huahaiy** [comment]
@borkdude Thanks for the pointers, I will look into these.

**Comment by littleli** [comment]
> We should make dtlv command line tool available for users to easily install, including installing the dependency (LMDB). For MacOS and Linux, we can use homebrew. For Windows, need to figure out. Also release datalevin as a babashka pod.

If you manage to build a native binary for Windows. I'll create manifest and add it to [clojure-scoop bucket](https://github.com/littleli/scoop-clojure).

**Comment by borkdude** [comment]
As for the pod:

> Also release datalevin as a babashka pod.

This can be part of the normal binary. See how clj-kondo is doing this for example:

https://github.com/clj-kondo/clj-kondo/blob/master/src/pod/borkdude/clj_kondo.clj

I recommend using transit as the payload format if you want to be able to store binary blobs in datalevin attributes. Else, EDN is fine (what clj-kondo uses).

This is a commit which shows how to move the payload format from EDN to transit:

https://github.com/babashka/babashka-sql-pods/commit/e8a5c771cda845c92c7073d862467e9c30118be3

**Comment by huahaiy** [comment]
@littleli I was able to build a native binary for Windows, https://github.com/juji-io/datalevin/releases/download/0.4.25/dtlv-0.4.25-windows-amd64.zip, could you take a look? Thanks.

**Comment by huahaiy** [comment]
Sent an PR for registering datalevin as a babashka pod. https://github.com/babashka/pod-registry/pull/10
