### ISSUE TITLE
Dynamic library path.

### ISSUE THREAD

**Issue by wildwestrom** [juji-io/datalevin#40]
So I'm testing on MacOS and I had to symlink the library for lmdb to do this:
 
```fish
ln -s ~/homebrew/Cellar/lmdb/lib/liblmdb.dylib /usr/local/opt/lmdb/lib/liblmdb.dylib
```

This is because Homebrew, as you can tell, is installed in a different location than it normally is.

Not sure how to fix it. Here's the original error.

```shellsession
$ dtlv help
dyld: Library not loaded: /usr/local/opt/lmdb/lib/liblmdb.dylib
  Referenced from: /Users/main/.local/bin/dtlv
  Reason: image not found
fish: 'dtlv help' terminated by signal SIGABRT (Abort)
```

**Comment by huahaiy** [comment]
When #38 is resolved, we will bundle LMDB in Datalevin, so this kind of problem should not happen any more.

**Comment by huahaiy** [comment]
Now LMDB is statically linked in our binary.
