### ISSUE TITLE
No implementation of method: :-find-vars of protocol: #'datalevin.parser/IFindVars found for class: datalevin.parser.Constant

### ISSUE THREAD

**Issue by cswaroop** [juji-io/datalevin#42]
When I executed the last part of README

(d/q '[:find (pull ?e [*])
       :in $ ?alias
       :where
       [?e :aka ?alias]]
     @conn
     "fred")

I got this error.
No implementation of method: :-find-vars of protocol: #'datalevin.parser/IFindVars found for class: datalevin.parser.Constant

Environment: Linux(Kali) running in Windows WSL2.

**Comment by conn** [comment]
I'm sorry, I don't know how to do that. You're going to have to teach me.

**Comment by huahaiy** [comment]
A fix is available in 04.13. Thanks for reporting!

**Comment by cswaroop** [comment]
works perfect.
