### ISSUE TITLE
Problem with :db/valueType :db.type/string

### ISSUE THREAD

**Issue by KaterMikesch** [juji-io/datalevin#43]
Hi, thanks for datalevin!

One thing that took a while to find out, was that specifying a string attribute with `:db/valueType :db.type/string` seem to mess up string encoding somehow/somewhere. German umlauts for example break when specifying the string type. When NOT specifying the attribute at all beforehand then the encoding stays intact. Don't know if this is because of using a blob when a type has not been specified ...

Hm ... can I help with this?

- Axel

**Comment by KaterMikesch** [comment]
Here a minimal example for reproducing this behavior:

```
(require '[datalevin.core :as d])

;; -- buggy (with type specified in schema) --
(def schema {:bug {:db/valueType :db.type/string}})
(def conn (d/get-conn "bug.db" schema))

(d/transact! conn [{:bug "Ümläüt"}])

(d/q '[:find (pull ?e [*])
       :where
       [?e :bug]]
     @conn)
;; => ([{:db/id 1, :bug "��ml����t"}])

(d/close conn)

;; -- correct (without type specified in schema) --
(def conn (d/get-conn "correct.db" {}))

(d/transact! conn [{:bug "Ümläüt"}])

(d/q '[:find (pull ?e [*])
       :where
       [?e :bug]]
     @conn)
;; => ([{:db/id 1, :bug "Ümläüt"}])
```

Please let me know if I can help more.

- Axel

**Comment by KaterMikesch** [comment]
Oh, version used is 0.4.18 btw. :-)

**Comment by huahaiy** [comment]
I cannot reproduce this error. Please let me know how this can be reproduced, e.g. on which OS, Java version, etc.

**Comment by KaterMikesch** [comment]
Hi, thanks for answering so quickly.

I'm on a Mac (Mac OS 11.2.2).
```
java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```
Clojure REPL via Emacs/Cider. deps.edn project.

I'll try with 0.4.19.

**Comment by KaterMikesch** [comment]
Same problem here with version 0.4.19. Unfortunately.
As if a 16 bit encoding is being used when the string type has been specified. Hm, strange.

**Comment by huahaiy** [comment]
Can you try 0.4.20? Thanks

**Comment by KaterMikesch** [comment]
I tried now outside of Emacs/Cider. In Terminal in the same project folder. REPL started via `clj`. The "bug" was gone.
Sorry for making waves here and thanks again for your help. 
The problem seems to be something with Emacs/Cider here. Will try in VS Code/Calva.

**Comment by KaterMikesch** [comment]
I will also try 0.4.20 in Emacs/Cider now.
...
0.4.20 changed the behavior. In the Cider REPL now the result of the `find pull` is 
`([{:db/id 1, :bug "?ml??t"}])`

No longer 16 bit strangeness but unknown chars or something like that. Will open the exact same db in Terminal via `clj` to see, if it's only a display issue in Emacs/Cider.
...
No, same result in Terminal.

=> 0.4.20 changed something here but we are not completely there. :-)

Maybe there is one little change more ... that fixes this issue (even for Emacs/Cider)? I will look at the diff between 0.4.19 and 0.4.20. The area in which the change happened seems to be relevant.

**Comment by KaterMikesch** [comment]
All looks good in VSCode/Calva.
Don't know if this issue should bother any longer ... what do you think?
Again, thanks a lot.

**Comment by huahaiy** [comment]
It seems to be it's an emacs configuration problem. See [Emacs Wiki](https://www.emacswiki.org/emacs/ChangingEncodings). It shows an example with exactly the same symptom as you described, and it can be fixed by an emacs command. 

I use Spacemacs, so everything is configured correctly already and I have never had this problem. 

I also like that 0.4.20 now relies on the default encoding of underlying JVM and trusts that it does the right thing. So I don't see what else we can do. 

Closing.

**Comment by huahaiy** [comment]
I thought about this a little more, relying on JVM default encoding looks a little dangerous, for it means that the database file will become un-transferable from one OS/locale to another. For example, the default encoding of JVM on Mac/Linux is UTF-8, but the default on Windows is not. We would like to have more control on encoding. So I have decided to use UTF-8 everywhere in our code base.

**Comment by KaterMikesch** [comment]
That kind of rubustness sounds really good.

Just tested version 0.4.22 with Emacs/Cider and it worked flawlessly.
Thanks once again.
