### ISSUE TITLE
Make it work with jdk16 without having to permit illegal access

### ISSUE THREAD

**Issue by huahaiy** [juji-io/datalevin#47]
Since JDK16, it is necessary to set "--illegal-access=permit"  JVM option for LMDBJava to work.  Maybe need to remove the dependency #35

**Comment by huahaiy** [comment]
In JDK17, this option is removed. So at the moment, JVM Datalevin does not work with it.

**Comment by jdf-id-au** [comment]
Using openjdk@17 from deps.edn needs the following within an alias (doesn't seem to work at toplevel!):
```clj
:jvm-opts ["--add-opens=java.base/java.nio=ALL-UNNAMED"
           "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"]
```

Adapted from https://github.com/lmdbjava/lmdbjava/commit/5687bd61ff8de770800fa319b4b98a0f61a92b24

**Comment by huahaiy** [comment]
This is resolved already.
