### ISSUE TITLE
`dtlv` quote seems to be resolving to syntax-quote, not quote

### ISSUE THREAD

**Issue by russmatney** [juji-io/datalevin#49]
Thanks for your continued work on datalevin - I integrated it into a clojure-y WM tool I'm working on today and it has been very useful, particularly the babashka pod integration - thanks much!

I hit a strange quirk while diving - before going for the pod, I was trying to wrap `dtlv` usage via the shell, but it seems that some datalog queries fail because of a quote/syntax-quote issue.

Here's a quick reproduction:
```
(def conn (get-conn "./somedb"))
(transact! conn [{:name "Datalevin"} {:some "value"} {:another "val"}])
(q (quote [:find ?e :where (or [?e :name "Datalevin"] [?e :some "value"])]) @conn)
(close conn)
```
```
❯ dtlv

  Datalevin (version: 0.4.28)

  Type (help) to see available functions. Clojure core functions are also available.
  Type (exit) to exit.

user> (def conn (get-conn "./somedb"))
#'user/conn
user> (transact! conn [{:name "Datalevin"} {:some "value"} {:another "val"}])
{:datoms-transacted 3}
user> (q (quote [:find ?e :where (or [?e :name "Datalevin"] [?e :some "value"])]) @conn)
Unknown rule 'clojure.core/or in (clojure.core/or [?e :name "Datalevin"] [?e :some "value"])
user>
```

The error shows `clojure.core/or` being attempted.

I ended up using the bb-pod and things work great that way, but I didn't want to leave this hanging.

**Comment by huahaiy** [comment]
Thank you for reporting the bug. This is fixed in 0.4.29.

**Comment by russmatney** [comment]
@huahaiy sorry for the acronym - I'm referring to a window-management tool, something like [i3](https://i3wm.org/) or [AwesomeWM](https://awesomewm.org/). What I have right now is kind of a Frankenstein of babashka-based clojure on top of AwesomeWM itself. I'm calling it [Clawe](https://github.com/russmatney/clawe). It's not quite ready to support other users yet, but I've been building it up for a few months now and am enjoying writing my keybindings ([here's an example](https://github.com/russmatney/clawe/blob/master/src/clawe/defs/bindings.clj#L77)) in repl-driven clojure.

**Comment by russmatney** [comment]
Also, thanks for the quick fix!

**Comment by huahaiy** [comment]
That's awesome :-)
