### ISSUE TITLE
Limit the size of in-memory transaction cache

### ISSUE THREAD

**Issue by huahaiy** [juji-io/datalevin#50]
If the system is running for an extended time, the in-memory transaction cache may grow to be too big for the heap. 

Need to come up with a policy to clean it up, e.g. a size limit (datom count) option set when opening the DB.

**Comment by ieugen** [comment]
> A cache without an eviction policy is a memory leak 

https://www.youtube.com/watch?v=E2KYTXKUsT4 .

**Comment by huahaiy** [comment]
We clear the transaction cache after each transaction.
