### ISSUE TITLE
Indicee

### ISSUE THREAD

**Issue by bongistan** [juji-io/datalevin#57]
Hi! How are indices defined in datalevin? I would like to create indices(composed of multiple fields) to have faster queries and am not sure how to do it. Thanks!

**Comment by huahaiy** [comment]
Datalevin is a triplestore, so all individual fields are already indexed automatically while writing the data.  The current query engine is inefficient, hence we are working on a new query engine. In addition, Datalevin is a library, so we will not support extra processes or threads to do extra work such as indexing. The additional composite indices, if we support them in the future, will also be part of the data write. 

In any case, we will finish the query engine rewrite, before considering features such as creating new indices. Hopefully such feature becomes unnecessary, as it does increases the complexity of operating a database, whereas our goal is to simplify data access.

**Comment by bongistan** [comment]
thanks

**Comment by huahaiy** [comment]
Our planned engine rewrite include a feature of `entity class`, which is defined as a composite of attributes that only appears together. These will be indexed during write. Hopefully, this will make the work of manual index creation obsolete.

**Comment by huahaiy** [comment]
When we land composite tuples (soon), this feature will become obsolete. Closing.

**Comment by huahaiy** [comment]
Composite tuples has landed. #168
