### ISSUE TITLE
Can I open from multiple processes? 

### ISSUE THREAD

**Issue by ieugen** [juji-io/datalevin#58]
I'm trying to open the database from multiple processes - a clojure repl and dtlv binary.

According to the lmdb documentation, this should be possible.
Any hints on how I may achieve this with datalevin?

I have copied the example from https://github.com/juji-io/datalevin#use-as-a-datalog-store and started a clojre repl inside calva.

Ran the lines to open a connection and the first query and stopped.

Then I ran `dtlv -d datalevin.lmdb -a stat` inside dtlv and I got the bellow errors:

````
dtlv -d datalevin.lmdb -a stat

clojure.lang.ExceptionInfo: Fail to open LMDB database: "MDB_VERSION_MISMATCH: Database environment version mismatch"
{:dir "datalevin.lmdb"}
 at datalevin.binding.graal$fn__4771.invokeStatic (graal.clj:564)
    datalevin.binding.graal/fn (graal.clj:555)
    clojure.lang.MultiFn.invoke (MultiFn.java:229)
    datalevin.main$dtlv_stat$fn__19813.invoke (main.clj:513)
    datalevin.main$dtlv_stat.invokeStatic (main.clj:512)
    datalevin.main$_main.invokeStatic (main.clj:583)
    datalevin.main$_main.doInvoke (main.clj:578)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    datalevin.main.main (:-1)
Stat error: Fail to open LMDB database: "MDB_VERSION_MISMATCH: Database environment version mismatch"

````

https://openldap.org/lists/openldap-technical/201406/msg00016.html

https://github.com/lmdbjava/lmdbjava/wiki/Concurrency

**Comment by huahaiy** [comment]
Of course you can. 

The error you encountered is about LMDB version mismatch. Basically, the JVM version runs  a LMDB that is different from the native one. The later is compiled from source ourselves, whereas the former is pulled from Maven by the LMDBJava dependency.

After we remove the LMDBJava dependency, #35, we will use the same LMDB version that we compile from the source.

**Comment by huahaiy** [comment]
Before the above fix is ready, a quick fix is to compile the same version of LMDB as LMDBJava does.
