### ISSUE TITLE
remote edge case: serialization breaks for d/entity used as a db function

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#66]
```clojure
(d/q '[:find ?ent
       :in $ ent
       :where
       [?e _ _]
       [(ent $ ?e) ?ent]]
     @conn d/entity)

;; => Execution error (ExceptionInfo) at datalevin.client.Connection/send_n_receive (client.clj:36).
;; Error sending message and receiving response:"Unfreezable type: class datalevin.core$entity"
```

**Comment by huahaiy** [comment]
Could you try wrapping `d/entity` in `inter-fn`? The remote function needs to be wrapped in `inter-fn` to be serializable.

**Comment by huahaiy** [comment]
Right. What would be the desired outcome for this? Send the content of the entity back as if it's touched, then recreate an entity object out of that content?

**Comment by den1k** [comment]
To avoid confusion, I think it should behave just like a local db would. So `Entity`'s  are returned containing only their `:db/id`s unless they have been touched.

So if the output of 
```clojure
(d/q '[:find ?e
       :in $
       :where
       [?e _ _]]
     @conn)
```
is `=> #{[4] [6] [3] [5] [2] [1]}`

then I think the output of 

```clojure
(d/q '[:find ?ent
       :in $ ent
       :where
       [?e _ _]
       [(ent $ ?e) ?ent]]
     @conn d/entity)
```
should be `=> #{[#:db{:id 4}] [#:db{:id 6}] [#:db{:id 3}] [#:db{:id 5}] [#:db{:id 2}] [#:db{:id 1}]}` where each `#:db{:id ...}` is an untouched `Entity`.  

If instead the query is
```
(d/q '[:find ?ent
       :in $ ent
       :where
       [?e _ _]
       [(ent $ ?e) ?ent]]
     @conn
     (fn [db eid]
       (d/touch (d/entity db eid))))
```
then the `Entity`'s should be recreated as touched.

**Comment by huahaiy** [comment]
Thanks for the illustration, this makes perfect sense. Would you be willing to take a crack at implementing this?

**Comment by den1k** [comment]
I'm not too confident I'll be able to make a dent but I could possibly take a look on the weekend.

That said, I think we have two issues here

- how does `$` (db) get handled to be passed into serialized functions (`inter-fn`?)
- how can entity be serialized and de-serialized using fressian while avoiding sending extra requests for each entity?

**Comment by huahaiy** [comment]
In other cases, `$` is handled by  being turned into a placeholder keyword, and replaced by a remote db on the server. 

The entity, as you outlined above, the first two cases are just going to be regular edn data, nothing special needs to be done. The thrid case needs some consideration, but it could be handled the same way as above, i.e. turn it into a placeholder keyword.

**Comment by den1k** [comment]
Amazing! 🚀
