### ISSUE TITLE
invalid reuse of reader locktable slot

### ISSUE THREAD

**Issue by huahaiy** [juji-io/datalevin#7]
Keep an old connection, use a new connection to transact, close the db. Try query on old connection, this error appears. Run the query second time, "transaction has not been reset" is thrown. 

One option is to open env with MDB_NOLOCK, but we need to make sure we manage locks ourselves.

**Comment by huahaiy** [comment]
http://www.lmdb.tech/doc/starting.html

> LMDB uses POSIX locks on files, and these locks have issues if one process opens a file multiple times. Because of this, do not mdb_env_open() a file multiple times from a single process. Instead, share the LMDB environment that has opened the file across all threads. Otherwise, if a single process opens the same environment multiple times, closing it once will remove all the locks held on it, and the other instances will be vulnerable to corruption from other processes.

**Comment by vkz** [comment]
Hi. Been pulling my hair until thought of checking the issues. This may still be a problem and IMO at least a note in the docs may help others. Easiest way to reproduce is something like this code (as you mentioned at the beginning):
```clj
(let [conn (store/connect "bob")]
  (let [conn (store/connect "bob")]
    (store/transact! conn [{:foo/boo "boo"}])
    (store/close conn))
  (store/transact! conn [{:foo/baz "baz"}])
  (store/close conn))
```

While one is unlikely to write this by hand, the following is a typical way to manage resources:
```clj
(store/with [conn "bob"]
  (store/with [conn "bob"]
    (store/transact! conn [{:foo/boo "boo"}]))
  (store/transact! conn [{:foo/baz "baz"}]))
```
and will  roughly expand into the first snippet.

With few databases one can have a service that simply holds on to connections. With lots of them however you need to manage resources somehow. Argument can be made that it isn't Datalevin's place to deal with it, and I think that's fair. People may choose to do their own connection pooling or ref counting or smth, but they need to know they have to do it.  Another option is to provide some lower level API to LMDB "environment" but I know nothing about LMDB to make reasonable suggestions.

**Comment by huahaiy** [comment]
Thank you for mentioning this. I have updated the doc string and exception message to make it more clear.

**Comment by vkz** [comment]
Thank you.

Re `with` I should've phrased it better. It has nothing to do with `datalevin`'s `with`. It is my own macro roughly similar to `with-open` e.g.

```clj
(defmacro with
  ""
  {:style/indent [1 [[:defn]] :form]}
  [[id conn] & body]
  `(let [conn# ~conn
         ~id (connect conn#)]
     (let [res# (do ~@body)
           forced# (if (coll? res#) (doall res#) res#)]
       ;; Only close a connection that we open here. Connection established outside "with" and passed
       ;; in as an argument should remain opened.
       (when-not (d/conn? conn#)
         ;; only close if still opened
         (when (d/conn? ~id)
           (d/close ~id)))
       forced#)))
```
issue I wanted to bring up had to do with someone, like me, writing something similar to the above thinking that  you could open and close connections at will, when in fact semantically managing connections as resource is not straightforward with limitations and requirements imposed by LMDB implementation.

**Comment by huahaiy** [comment]
I don't think Datalevin or LMDB is special in anyway compared with any other stateful database. 

For example,  in Clojure, I have not seen anybody attempts to use a Postgres connection with something resembles a `with-open`, so I am not sure where this assumption comes from and why you would expect to connect to a database using that.  I think it is sufficient to tell people that Datalevin should be managed like any other stateful resources and give recommendation on what to use, i.e. a component like life cycle management tool that is commonly used for these use cases.

 I would submitted that only a very small minority of Clojure users would think to write their own macros to do this kind of things. If they can write their own macro to manage a database connection, it is not that hard to do what Datalevin is asking them to do. 

In any case, what I want to reiterate, is that there's nothing special or particularly burdensome for users in the case of  Datalevin or LMDB for that matter.

**Comment by huahaiy** [comment]
Release 0.3.9 added `with-conn` macro and `get-conn` function to reuse the same connection to the same database, if desired.
