### ISSUE TITLE
Add a `migr` command to migrate server data

### ISSUE THREAD

**Issue by huahaiy** [juji-io/datalevin#71]
As a server may host many databases, it is more convenient to use a command to take care of the chores of dumping and loading a lot of databases.

**Comment by jdf-id-au** [comment]
Thanks for this completely magnificent library.

I encountered some trouble trying to dump/load a db with evil space-containing keywords. [This approach](https://gist.github.com/jdf-id-au/80e3be174de2b3fe1a91894b2ee2f0e3) works around the limitations of [serialising with `prn`](https://github.com/juji-io/datalevin/blob/fd89f8cc4cc73771244e9b779ecbf5f6bfffa9c5/src/datalevin/core.cljc#L1464). ([This comment](https://github.com/juji-io/datalevin/issues/151#issuecomment-1400618653) is vaguely relevant on a quick search.)

**Comment by huahaiy** [comment]
Sure.

**Comment by huahaiy** [comment]
This is superseded by #276.
