### ISSUE TITLE
Could not initialize class org.lmdbjava.ByteBufferProxy

### ISSUE THREAD

**Issue by julienfantin** [juji-io/datalevin#73]
Following the README I get the error below when calling `d/get-conn`

```
2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling NO_SOURCE_FILE at (19:3)
   {:clojure.error/column 3,
    :clojure.error/line 19,
    :clojure.error/phase :execution,
    :clojure.error/source "NO_SOURCE_FILE"}

1. Caused by java.lang.NoClassDefFoundError
   Could not initialize class org.lmdbjava.ByteBufferProxy

              storage.cljc:  496  datalevin.storage$open/invokeStatic
              storage.cljc:  486  datalevin.storage$open/invoke
                   db.cljc:  305  datalevin.db$open_store/invokeStatic
                   db.cljc:  297  datalevin.db$open_store/invoke
                   db.cljc:  328  datalevin.db$empty_db/invokeStatic
                   db.cljc:  321  datalevin.db$empty_db/invoke
                   db.cljc:  324  datalevin.db$empty_db/invokeStatic
                   db.cljc:  321  datalevin.db$empty_db/invoke
                 core.cljc:  460  datalevin.core$create_conn/invokeStatic
                 core.cljc:  433  datalevin.core$create_conn/invoke
                 core.cljc:  700  datalevin.core$new_conn/invokeStatic
                 core.cljc:  697  datalevin.core$new_conn/invoke
                 core.cljc:  714  datalevin.core$get_conn/invokeStatic
                 core.cljc:  705  datalevin.core$get_conn/invoke
```

This machine is an Apple M1 running:

```
❯ clojure -version
Clojure CLI version 1.10.3.943

❯ java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Homebrew (build 17+0)
OpenJDK 64-Bit Server VM Homebrew (build 17+0, mixed mode, sharing)
```

**Comment by huahaiy** [comment]
You may want to paste the full report of /var/folders/qc/9tgh66px2yjb_p4wbqq1j4fm0000gn/T/clojure-16909923315892362026.edn

**Comment by huahaiy** [comment]
Now I cleaned up the warning a bit in the benchmark:

```
❯ ./bench.clj
WARNING: Implicit use of clojure.main with options is deprecated, use -M
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Warning: implicit hook found: lein-environ.plugin/hooks
Hooks are deprecated and will be removed in a future version.
Compiling 10 source files to /Users/huahaiy/workspace/datalevin/target/classes
version   	q1 	q2 	q3 	q4 	qpred1 	qpred2
latest-datascript 	3.5 	8.7 	12.6 	18.9 	12.7 	37.0
latest-datalevin 	1.2 	4.9 	5.7 	8.9 	10.2 	11.9
```
As you can see, a bunch of warnings are still coming from some lein plugins that I have.

**Comment by den1k** [comment]
FYI while LMDBJava still doesn’t seem to support M1, graal does now support it according to this update: https://github.com/oracle/graal/issues/2666#issue-654797437

**Comment by kbosompem** [comment]
i tried so many things and it is now working but not sure what really worked Incase anyone runs into this issue

1. Using the latest graalvm 22.2.0-dev
2. excluded lmdbjava from datalevin
3. required lmdbjava 0.8.3-snapshot
4. I also followed the instructions [here](https://github.com/lmdbjava/native/issues/10) and copied the liblmdb.dyliblib to /usr/local/lib
5. For leiningen i also had to set  LEIN_SNAPSHOTS_IN_RELEASE to true to use the 0.8.3 snapshot. 

My project.clj looks as follows

`(defproject spcmig "0.1.0"
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [dk.ative/docjure "1.17.0"]
                 [http-kit "2.6.0-alpha1"]
                 [cheshire "5.11.0"]
                 [com.taoensso/timbre "5.2.1"]
                 [org.lmdbjava/lmdbjava "0.8.3-SNAPSHOT"]
                 [datalevin "0.6.13" :exclusions [org.lmdbjava/lmdbjava]]]
  :plugins  [[lein-ancient "1.0.0-RC4-SNAPSHOT"]
             [jonase/eastwood "1.2.3"]]
  :main spcmig.core
  :uberjar-name "s2e.jar"
  :jar-name "spcmig.jar"
  :profiles {:uberjar {:aot :all}}
  :jvm-opts ^:replace ["-Dclojure.compiler.direct-linking=true"
                       "--add-opens=java.base/java.nio=ALL-UNNAMED"
                       "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"]
  :repl-options {:init-ns spcmig.core})`

**Comment by huahaiy** [comment]
For adding the jvm-opts to `deps.edn`, here's an example:

```
:aliases {:jvm-base
           {:jvm-opts ["--add-opens=java.base/java.nio=ALL-UNNAMED"
                       "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"]}}
```
Then `clj -A:jvm-base`

**Comment by huahaiy** [comment]
For lein, the project.clj likes a slightly different syntax for jvm-opts. Here are what's in Datalevin's own project.clj:

```
                              :jvm-opts
                              ["--add-opens" "java.base/java.nio=ALL-UNNAMED"
                               "--add-opens" "java.base/java.lang=ALL-UNNAMED"
                               "--add-opens" "java.base/sun.nio.ch=ALL-UNNAMED"
                               "--add-opens" "java.base/jdk.internal.ref=ALL-UNNAMED"]

```

**Comment by huahaiy** [comment]
> I tried so many things and it is now working but not sure what really worked Incase anyone runs into this issue [this](https://0110.be/posts/Using_Java_LMDB_on_Apple_Sillicon_or_other_unsupported_platforms) was the most helpful resource
> 
> 1. Using the latest graalvm 22.2.0-dev
> 2. excluded lmdbjava from datalevin
> 3. required lmdbjava 0.8.3-snapshot
> 4. I also followed the instructions [here](https://github.com/lmdbjava/native/issues/10) and copied the liblmdb.dyliblib to /usr/local/lib
> 5. For leiningen i also had to set  LEIN_SNAPSHOTS_IN_RELEASE to true to use the 0.8.3 snapshot.
> 
> My project.clj looks as follows
> 
> ```
>  (defproject spcmig "0.1.0"
>   :dependencies [[org.clojure/clojure "1.11.1"]
>                              [dk.ative/docjure "1.17.0"]
>                  [http-kit "2.6.0-alpha1"]
>                  [cheshire "5.11.0"]
>                  [com.taoensso/timbre "5.2.1"]
>                  [org.lmdbjava/lmdbjava "0.8.3-SNAPSHOT"]
>                  [datalevin "0.6.13" :exclusions [org.lmdbjava/lmdbjava]]]
>   :plugins  [[lein-ancient "1.0.0-RC4-SNAPSHOT"]
>              [jonase/eastwood "1.2.3"]]
>   :main spcmig.core
>   :uberjar-name "s2e.jar"
>   :jar-name "spcmig.jar"
>   :profiles {:uberjar {:aot :all}}
>   :jvm-opts ^:replace ["-Dclojure.compiler.direct-linking=true"
>                        "--add-opens=java.base/java.nio=ALL-UNNAMED"
>                        "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"]
>   :repl-options {:init-ns spcmig.core})
> ```

This should now work out of box. No need to mess with these now.
