### ISSUE TITLE
Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module

### ISSUE THREAD

**Issue by JerroldJacobsen** [juji-io/datalevin#77]
trivial program causes error. Here is terminal list, the program, and full error.

(ns datalevin2.core
  (:gen-class))
(require '[datalevin.core :as d])
(defn -main [& args]
;; Open a key value DB on disk and get the DB handle
(def db (d/open-kv "/tmp/datalevin/mykvdb"))
)

Syntax error (InaccessibleObjectException) compiling at (/private/var/folders/b6/kqd4dc516q10q1tskmzg341w0000gq/T/form-init2511322920906303443.clj:1:125).
Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @2545bd49

Full report at:
/var/folders/b6/kqd4dc516q10q1tskmzg341w0000gq/T/clojure-628545594777319041.edn

{:clojure.main/message
 "Syntax error (InaccessibleObjectException) compiling at (/private/var/folders/b6/kqd4dc516q10q1tskmzg341w0000gq/T/form-init2511322920906303443.clj:1:125).\nUnable to make field long java.nio.Buffer.address accessible: module java.base does not \"opens java.nio\" to unnamed module @2545bd49\n",
 :clojure.main/triage
 {:clojure.error/phase :compile-syntax-check,
  :clojure.error/line 1,
  :clojure.error/column 125,
  :clojure.error/source "form-init2511322920906303443.clj",
  :clojure.error/path
  "/private/var/folders/b6/kqd4dc516q10q1tskmzg341w0000gq/T/form-init2511322920906303443.clj",
  :clojure.error/class java.lang.reflect.InaccessibleObjectException,
  :clojure.error/cause
  "Unable to make field long java.nio.Buffer.address accessible: module java.base does not \"opens java.nio\" to unnamed module @2545bd49"},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message
    "Syntax error compiling at (/private/var/folders/b6/kqd4dc516q10q1tskmzg341w0000gq/T/form-init2511322920906303443.clj:1:125).",
    :data
    {:clojure.error/phase :compile-syntax-check,
     :clojure.error/line 1,
     :clojure.error/column 125,
     :clojure.error/source
     "/private/var/folders/b6/kqd4dc516q10q1tskmzg341w0000gq/T/form-init2511322920906303443.clj"},
    :at [clojure.lang.Compiler load "Compiler.java" 7652]}
   {:type java.lang.ExceptionInInitializerError,
    :at
    [org.lmdbjava.ByteBufferProxy <clinit> "ByteBufferProxy.java" 71]}
   {:type java.lang.reflect.InaccessibleObjectException,
    :message
    "Unable to make field long java.nio.Buffer.address accessible: module java.base does not \"opens java.nio\" to unnamed module @2545bd49",
    :at
    [java.lang.reflect.AccessibleObject
     checkCanSetAccessible
     "AccessibleObject.java"
     354]}],
  :trace
  [[java.lang.reflect.AccessibleObject
    checkCanSetAccessible
    "AccessibleObject.java"
    354]
   [java.lang.reflect.AccessibleObject
    checkCanSetAccessible
    "AccessibleObject.java"
    297]
   [java.lang.reflect.Field checkCanSetAccessible "Field.java" 178]
   [java.lang.reflect.Field setAccessible "Field.java" 172]
   [org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy
    findField
    "ByteBufferProxy.java"
    163]
   [org.lmdbjava.ByteBufferProxy$ReflectiveProxy
    <clinit>
    "ByteBufferProxy.java"
    222]
   [org.lmdbjava.ByteBufferProxy <clinit> "ByteBufferProxy.java" 71]
   [org.lmdbjava.Env create "Env.java" 92]
   [datalevin.binding.java$eval6328$fn__6329 invoke "java.clj" 447]
   [clojure.lang.MultiFn invoke "MultiFn.java" 229]
   [datalevin.core$open_kv invokeStatic "core.cljc" 883]
   [datalevin.core$open_kv invoke "core.cljc" 856]
   [datalevin2.core$_main invokeStatic "core.clj" 6]
   [datalevin2.core$_main doInvoke "core.clj" 4]
   [clojure.lang.RestFn invoke "RestFn.java" 397]
   [clojure.lang.Var invoke "Var.java" 380]
   [user$eval140 invokeStatic "form-init2511322920906303443.clj" 1]
   [user$eval140 invoke "form-init2511322920906303443.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7181]
   [clojure.lang.Compiler eval "Compiler.java" 7171]
   [clojure.lang.Compiler load "Compiler.java" 7640]
   [clojure.lang.Compiler loadFile "Compiler.java" 7578]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$init_opt invokeStatic "main.clj" 477]
   [clojure.main$init_opt invoke "main.clj" 477]
   [clojure.main$initialize invokeStatic "main.clj" 508]
   [clojure.main$null_opt invokeStatic "main.clj" 542]
   [clojure.main$null_opt invoke "main.clj" 539]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "Unable to make field long java.nio.Buffer.address accessible: module java.base does not \"opens java.nio\" to unnamed module @2545bd49",
  :phase :compile-syntax-check}}

**Comment by huahaiy** [comment]
From README:

This JVM library supports Java 8 and above. For JVM version newer than 11, you may want to add the following JVM options:

--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
Or you will get errors such as "Could not initialize class org.lmdbjava.ByteBufferProxy".

**Comment by theronic** [comment]
As per README, need to use [an alias](https://cljdoc.org/d/datalevin/datalevin/0.8.18/doc/installation#clojure-library) when using deps.edn.
