### ISSUE TITLE
Specify an Executor in the IndexSearcher constructor

### ISSUE THREAD

**Issue by cavallium** [juji-io/datalevin#78]
IndexSearcher has two constructors:

1.  `IndexSearcher(IndexReader r)`
2.  `IndexSearcher(IndexReader r, Executor executor)`

The second constructor allows lucene to compute each slice independently.

Here you used the one without the executor:
https://github.com/juji-io/datalevin/blob/d880005010dc224c095e2dfd4dbfd84b1dde30cf/search-bench/src/lucene/bench.clj#L53

I'm not 100% sure if this will improve the performance, but it's very likely.

**Comment by huahaiy** [comment]
Feel free to send a PR. Thanks.

**Comment by huahaiy** [comment]
That would be an unfair comparison. The point of benchmarking is to have the equal conditions for all contestants. 

In addition, I do not believe this will make any material difference. The burden is on whoever says so to prove it. 

Closing.

**Comment by cavallium** [comment]
> That would be an unfair comparison. The point of benchmarking is to have the equal conditions for all contestants.
> 
> In addition, I do not believe this will make any material difference. The burden is on whoever says so to prove it.
> 
> Closing.

You need to add just a parameter in a language that you know well and you call this a burden of proof?

I have willingly contributed to the extent that I could, reporting all the problems I have found in the benchmarks, but since you have ignored them all I can only see the bad faith in continuing to feature these benchmarks as the basis for the claims made.

**Comment by huahaiy** [comment]
You did not understand my point. If I added that to Lucene, I would have to do the same to Datalevin. 

If I believe passing in a thread pool will somehow improve the performance, I would do that, but I do not believe so. Hence I need proof. Understood?
