### ISSUE TITLE
currentTimeMillis should not be used to create benchmarks

### ISSUE THREAD

**Issue by cavallium** [juji-io/datalevin#79]
CurrentTimeMillis is not suited for benchmarking, because it doesn't guarantee the use of the high precision timer.

From the java documentation:

https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#currentTimeMillis--

https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#nanoTime--

**Comment by huahaiy** [comment]
Please send a PR. Thanks.

**Comment by cavallium** [comment]
Ok

**Comment by huahaiy** [comment]
Merged. Closing.
