### ISSUE TITLE
Lucene benchmark query parsing is badly implemented

### ISSUE THREAD

**Issue by cavallium** [juji-io/datalevin#81]
> Lucene query parser seems to be rather picky. We had to manually fix some queries for the test to run. E.g. Lucene crashed with the query ""ground beef recipes'" for the mismatched quotes. The parser did not support concurrent query. A new parser has to be created for each query, otherwise the program would crash if there were more than one thread searching. Basically, some engineering effort is required for it to be suitable for end user facing applications.

Lucene "classic" QueryParser is the old parser, [StandardQueryParser](https://lucene.apache.org/core/8_0_0/queryparser/org/apache/lucene/queryparser/flexible/standard/StandardQueryParser.html) is the new one.

By the way, since you are benchmarking the search speed, you should exclude the string syntax parser from the lucene query times.

Otherwise, if you really want to keep them in the query times, it's better to create directly the query objects instead of parsing strings.

**Comment by fungiboletus** [comment]
> By the way, since you are benchmarking the search speed, you should exclude the string syntax parser from the lucene query times.

Why ? Isn't this part of the search ? You are not measuring the search speed anymore if you remove some parts of it.

**Comment by cavallium** [comment]
> > By the way, since you are benchmarking the search speed, you should exclude the string syntax parser from the lucene query times.
> 
> Why ? Isn't this part of the search ? You are not measuring the search speed anymore if you remove some parts of it.

I'm not removing parts randomly.

The speed of the string parser is completely unrelated to the speed of the search.

They are two different phases.

Also, the query parser initialization time should not be included anyway, since usually you should initialize it once at the start of your program.

**Comment by fungiboletus** [comment]
But if Lucene requires a string parser to do a search, from a human computer interaction point of view, this for sure needs to be included in the benchmark.

I agree that it could be initialised once, if it has a big impact.

**Comment by cavallium** [comment]
> But if Lucene requires a string parser to do a search, from a human computer interaction point of view, this for sure needs to be included in the benchmark.
> 
> I agree that it could be initialised once, if it has a big impact.

It absolutely does not require a string parser. I have personally seen lot of cases when the program just creates term queries, phrase queries or fuzzy queries directly, because it's not always a good thing to allow end users to directly create queries, it could lead to voluntary or involuntary DoS attacks, and other similar problems.

**Comment by cavallium** [comment]
> If the query parser is optional, please send a PR to do that.
> 
> As I mentioned in the benchmark README, "initializing the query parse only once" will crash Lucene, which does not support concurrent use of the query parser.

You used the legacy parser, you should use the updated parser:
https://lucene.apache.org/core/8_0_0/queryparser/org/apache/lucene/queryparser/flexible/standard/StandardQueryParser.html

**Comment by huahaiy** [comment]
Please send a PR. I appreciate it.

**Comment by cavallium** [comment]
> Please send a PR. I appreciate it.

I can't, I don't know Clojure

**Comment by huahaiy** [comment]
You don't need to write in Clojure, just write in Java, right here, I will translate that into clojure.

**Comment by cavallium** [comment]
> You don't need to write in Clojure, just write in Java, right here, I will translate that into Clojure.
> 
> If you are really interested and determined, I am about to submit a talk to an industrial conference. If you can implement T-Wand in Lucene, that would be perfect, you can be one of the authors of the talk, and get to send a PR to Lucene, sounds good?

Looks absolutely good, but I'm still too busy (university + personal projects that absorb too much time) to work on other people's projects.

**Comment by huahaiy** [comment]
In that case, I will close this issue. 

Thanks for sending the previous PR. I appreciate that.
