### ISSUE TITLE
Unable to use a custom function inside query when using babashka pod

### ISSUE THREAD

**Issue by timmw** [juji-io/datalevin#85]
When using datalevin in babashka and attempting to use a non built in function within a query, the following error occurs: 
"Unknown function '<function name> in [(<function name>)  ?x]" ([code](https://github.com/juji-io/datalevin/blob/73213c6d35e726a5be1d00b5b1ccbe15bb0fea9a/src/datalevin/query.cljc#L619))

It would be great if this worked. I did some basic investigation into getting this working but struggled to wrap my head around how babashka pods work.

**Comment by den1k** [comment]
Could you provide a full code example?

**Comment by timmw** [comment]
Sorry for delay. Here it is

```clj
; example.clj
(require '[babashka.pods :as pods])

(pods/load-pod 'huahaiy/datalevin "0.5.14")

(require '[pod.huahaiy.datalevin :as d])

(def conn (d/get-conn "/tmp/mydb"))

(defn custom-fn
    []
    "hello")

(d/q '[:find ?greeting
       :in $
       :where
       [(custom-fn) ?greeting]]
     (d/db conn))
```

```
> bb --version
babashka v0.7.3
> bb example.clj
Downloading pod huahaiy/datalevin (0.5.14)
Successfully installed pod huahaiy/datalevin (0.5.14)
#error {
 :cause Unknown function 'custom-fn in [(custom-fn) ?greeting]
 :data {:error :query/where, :form [(custom-fn) ?greeting], :var custom-fn}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message Unknown function 'custom-fn in [(custom-fn) ?greeting]
   :data {:error :query/where, :form [(custom-fn) ?greeting], :var custom-fn}
   :at [datalevin.query$bind_by_fn invokeStatic query.cljc 618]}]
 :trace
 [[datalevin.query$bind_by_fn invokeStatic query.cljc 618]
  [datalevin.query$_resolve_clause invokeStatic query.cljc 833]
  [datalevin.query$_resolve_clause invoke query.cljc 829]
  [datalevin.query$_resolve_clause invokeStatic query.cljc 831]
  [datalevin.query$resolve_clause invokeStatic query.cljc 918]
  [datalevin.query$resolve_clause invoke query.cljc 914]
  [clojure.lang.ArraySeq reduce ArraySeq.java 111]
  [clojure.core$reduce invokeStatic core.clj 6829]
  [datalevin.query$_q invokeStatic query.cljc 960]
  [datalevin.query$q invokeStatic query.cljc 1109]
  [datalevin.query$q doInvoke query.cljc 1096]
  [clojure.lang.RestFn applyTo RestFn.java 139]
  [clojure.core$apply invokeStatic core.clj 669]
  [datalevin.core$q invokeStatic core.cljc 196]
  [datalevin.core$q doInvoke core.cljc 183]
  [clojure.lang.RestFn applyTo RestFn.java 139]
  [clojure.core$apply invokeStatic core.clj 669]
  [pod.huahaiy.datalevin$q invokeStatic datalevin.clj 60]
  [pod.huahaiy.datalevin$q doInvoke datalevin.clj 60]
  [clojure.lang.RestFn applyTo RestFn.java 139]
  [clojure.core$apply invokeStatic core.clj 667]
  [pod.huahaiy.datalevin$run$fn__19609 invoke datalevin.clj 417]
  [pod.huahaiy.datalevin$run invokeStatic datalevin.clj 410]
  [datalevin.main$_main invokeStatic main.clj 564]
  [datalevin.main$_main doInvoke main.clj 550]
  [clojure.lang.RestFn invoke RestFn.java 397]
  [clojure.lang.AFn applyToHelper AFn.java 152]
  [clojure.lang.RestFn applyTo RestFn.java 132]
  [datalevin.main main nil -1]]}
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Unknown function 'custom-fn in [(custom-fn) ?greeting]
Data:     {:error :query/where, :form [(custom-fn) ?greeting], :var custom-fn, :type "class clojure.lang.ExceptionInfo"}
Location: /home/tim/projects/datalevin-babashka-custom-function/example.clj:13:1

----- Context ------------------------------------------------------------------
 9: (defn custom-fn
10:     []
11:     "hello")
12: 
13: (d/q '[:find ?greeting
    ^--- Unknown function 'custom-fn in [(custom-fn) ?greeting]
14:        :in $
15:        :where
16:        [(custom-fn) ?greeting]]
17:      (d/db conn))
18: 

----- Stack trace --------------------------------------------------------------
babashka.pods.impl/processor         - <built-in>
babashka.pods.sci/load-pod/fn--30764 - <built-in>
user                                 - /home/tim/projects/datalevin-babashka-custom-function/example.clj:13:1
```

**Comment by spieden** [comment]
I believe this is expected because pods run in a separate process and so won't see the function you define.

**Comment by den1k** [comment]
@timmw try defining your function using `inter-fn` https://github.com/juji-io/datalevin/blob/cc6c82faeede57b5fd6b517a76ce5e5938df1a6e/src/datalevin/interpret.cljc#L117-L126 or wrap your existing function in
https://github.com/juji-io/datalevin/blob/cc6c82faeede57b5fd6b517a76ce5e5938df1a6e/src/datalevin/interpret.cljc#L134-L140

**Comment by timmw** [comment]
Unfortunately that didn't work for me:

```
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  Could not find namespace: pod.huahaiy.datalevin.interpret.
Location: 5:1
```

```clojure
(require '[babashka.pods :as pods])

(pods/load-pod 'huahaiy/datalevin "0.5.14")

(require '[pod.huahaiy.datalevin :as d]
         '[pod.huahaiy.datalevin.interpret :refer [inter-fn]])

(def conn (d/get-conn "/tmp/mydb"))

(def custom-fn (inter-fn
                []
                "hello"))

(d/q '[:find ?greeting
       :in $
       :where
       [(custom-fn) ?greeting]]
     (d/db conn))
```

It seems the datalevin babashka pod doesn't expose the datalevin.interpret namespace

**Comment by den1k** [comment]
@borkdude any insights on this one?

**Comment by borkdude** [comment]
@den1k I'll take a look at this in the weekend!

**Comment by borkdude** [comment]
Functions cannot be serialized but perhaps it's possible to define functions on the pod side using a special pod function.

**Comment by den1k** [comment]
@borkdude is there a reason functions can't be serialized beyond the `inter-fn` from https://github.com/juji-io/datalevin/blob/cc6c82faeede57b5fd6b517a76ce5e5938df1a6e/src/datalevin/interpret.cljc#L117-L126 not being exposed?

**Comment by huahaiy** [comment]
I have spent quite some time investigating this before settle on `inter-fn` approach. My conclusion is that function serialization cannot be done at this time if GraalVM support is needed. RedPlanet Lab's approach requires Clojure `eval`, and I have tried to fit that code with SCI `eval`, but failed, maybe I am not familiar enough with SCI. It would be great that sci can support RedPlanet Lab's approach.

**Comment by borkdude** [comment]
The issue is that the function should run in the same environment as where the the query is executed. The pod runs in a different environment as babashka. So the function should be defined in the pod environment, similar to how you would install a Datomic function: https://docs.datomic.com/on-prem/reference/database-functions.html.

**Comment by borkdude** [comment]
It seems that inter-fn is trying to send functions as s-expressions and evals them on the pod side right? Then what is the remaining issue?

**Comment by huahaiy** [comment]
`inter-fn` should work for Datalevin. The only remaining issue is that it is not exposed in the pod namespace, which I will do.

**Comment by borkdude** [comment]
@huahaiy Sounds good. Let me know if you need any help with SCI.

**Comment by huahaiy** [comment]
A macro `defpodfn` is provided to allow defining a custom function that can be used in query for pods.
