### ISSUE TITLE
Should :db/created-at and :db/updated-at be added

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#86]
Unlike datomic, datalevin has no concept of time. I've written various functions to add `:db/created-at` and `:db/updated-at` values. However, it's easy to forget invoking those helper fns in a call to `d/transact` which results in false data.  Should this maybe be a configurable option during `create-conn`?

**Comment by huahaiy** [comment]
You mean adding these attributes automatically for each entity?

**Comment by den1k** [comment]
Yes! Though not necessarily by default. This could be enabled through a config or fn call during init or even implicitly through the schema.

**Comment by huahaiy** [comment]
PR welcome.

**Comment by den1k** [comment]
hi @huahaiy thank you so much for working on this feature!

I've looked at your WIP changes and wanted to share one observation:
it looks like the schema for the time keys is hardcoded and merged in during init https://github.com/juji-io/datalevin/blob/3a1328b50b5aa6eb62434d9a876e1fd8e7e0acff/src/datalevin/constants.cljc#L20-L24
the issue is that this way the user cannot specify attribute key vals like `:db/index true` in case they want to be able to use datoms around timestamps which is useful to quickly lookup recently changed entities.

One idea is to configure the feature on the attribute in the schema similar to full-text search. E.g. if the user adds a `:db/created-at` key to the schema, the feature gets enabled while retaining the flexibility of adding additional keys like `:db/index`.

Since the keys are namespaced with `db` it's implied that this is the database's business to maintain just like `:db/id`. Here's what a schema could look like

```clojure
(def schema
  {:db/created-at {}
   :db/updated-at {:db/index true}})
```

Alternatively the implicit schema and the user-defined schemas could be deep-merged. That way your current WIP work could stay mostly the same but users can still add `:db/index` if needed.

**Comment by huahaiy** [comment]
We do not have `:db/index` at all. 

One can always add additional properties to existing schema items, regardless if they are built-in or not.
