### ISSUE TITLE
Error opening database: `Unable to make field long java.nio.Buffer.address accessible`

### ISSUE THREAD

**Issue by cpdean** [juji-io/datalevin#87]
When opening a new database, I get the following error:

```
(def datalevin-conn (d/get-conn "tmp/my-new-db" ))
Execution error (InaccessibleObjectException) at java.lang.reflect.AccessibleObject/checkCanSetAccessible (AccessibleObject.java:354).
Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @2545bd49
```

I'm on an M1 mac, so my issue could be related to https://github.com/juji-io/datalevin/issues/73#issuecomment-941866349, but the error I see is different from the specific one over there, so I'm hoping that there's a different way to fix my problem.  I've attempted to follow the instructions for compiling lmdb locally and setting the `lmdbjava.native.lib` system property to the location of both liblmdb.a and liblmdb.dylib, but so far the error remains the same.

**Comment by den1k** [comment]
@cpdean have you tried using `d/create-conn`? `d/get-conn` is for existing open connections according to the docs.

**Comment by cpdean** [comment]
ah there we go -- now i'm getting the same error message in the linked ticket

```
datomic-datalevin.core=> (def datalevin-conn (d/create-conn "tmp/crates-io.datalevin" ))

Execution error (NoClassDefFoundError) at org.lmdbjava.Env/create (Env.java:92).
Could not initialize class org.lmdbjava.ByteBufferProxy
```

@den1k thanks for pointing that out! i was using `d/get-conn` following along with the example [in the readme](https://github.com/juji-io/datalevin#use-as-a-datalog-store) which used to work for me on intel but now i'm stuck on my M1 blocker.

**Comment by theronic** [comment]
I am getting:
```
(d/create-conn "./data/mydb")
Execution error (ExceptionInInitializerError) at org.lmdbjava.ByteBufferProxy/<clinit> (ByteBufferProxy.java:71).
Exception java.lang.ExceptionInInitializerError [in thread "nREPL-session-6544ad0c-8969-4cd0-a88f-9cc0e5ce7874"]
```

Happens even if I delete data path.

**Comment by den1k** [comment]
Can't reproduce in Mac Silicon.

Which OS/hardware?

**Comment by theronic** [comment]
Was missing jvm-opts, thx!
