### ISSUE TITLE
deps.edn compatability & possibly github actions build

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#98]
Currently Datalevin cannot be used locally or remotely through Clojure Deps' git deps. The reason seems to be that [a few java files](https://github.com/juji-io/datalevin/tree/master/src/java/datalevin/io) need to be compiled ahead of time.

This blocks integration of datalevin forks into deps.edn projects (both locally and through git deps) and puts pressure on maintainers (@huahaiy) to cut releases with every new change.

At the same time there've been advances in Clojure tooling. For example tools.build allows arbitrary Clojure code to [build mixed dependencies](https://clojure.org/guides/tools_build#_mixed_java_clojure_build). Given that many Clojure projects today use deps.edn I think it would be a good idea to fix deps.edn compatibility and possibly add a build script for github actions such that forks can immediately be used in projects through git libs.

**Comment by huahaiy** [comment]
Sounds like a good idea. PR welcome.

**Comment by ieugen** [comment]
I'm going to take a look at this.

**Comment by ieugen** [comment]
I think this can be closed.

**Comment by huahaiy** [comment]
Thanks.

**Comment by den1k** [comment]
Amazing, thanks @ieugen !
