### ISSUE TITLE
Is there is a way to delete a schema item which has no datoms related to it?

### ISSUE THREAD

**Issue by wangchunsen** [juji-io/datalevin#99]
It seems there it only allows add item to schema, and not able to delete item from the schema. I think it is reasonable to delete schema which has no datoms related to it.

**Comment by huahaiy** [comment]
I would like to see a use case where this would be useful.

**Comment by huahaiy** [comment]
Schema migration will be addressed in a later version. We will address this when that happens.

**Comment by den1k** [comment]
I have a current use case for this: users are provided with a data entry interface where existing attributes are searched based on the schema and new attributes can be created and deleted. Currently the only way to support deletion is to also track attributes which have been deleted and ignore these from the schema.

There are also other parts where queries are built dynamically based on the schema. E.g. give me all unique identities of the `:user` namespace. Without deletion this results in additional queries/index calls to the DB.

**Comment by huahaiy** [comment]
Sounds reasonable.

**Comment by huahaiy** [comment]
`update-schema` takes an extra argument for a set of attributes to be deleted. Will throw if an attribute has datom related to it.
